// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces/user_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/interfaces/user_repository.go -destination=tests/mocks/user_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2025_2_RoadTo200/backend/internal/domain/entities"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), user)
}

// Delete mocks base method.
func (m *MockUserRepository) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepository)(nil).Delete), id)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), email)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), id)
}

// GetByPhone mocks base method.
func (m *MockUserRepository) GetByPhone(phone string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPhone", phone)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPhone indicates an expected call of GetByPhone.
func (mr *MockUserRepositoryMockRecorder) GetByPhone(phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPhone", reflect.TypeOf((*MockUserRepository)(nil).GetByPhone), phone)
}

// GetUsersByIDs mocks base method.
func (m *MockUserRepository) GetUsersByIDs(ids []uuid.UUID) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByIDs", ids)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByIDs indicates an expected call of GetUsersByIDs.
func (mr *MockUserRepositoryMockRecorder) GetUsersByIDs(ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByIDs", reflect.TypeOf((*MockUserRepository)(nil).GetUsersByIDs), ids)
}

// GetUsersForFeed mocks base method.
func (m *MockUserRepository) GetUsersForFeed(userID uuid.UUID, limit, offset int) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersForFeed", userID, limit, offset)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersForFeed indicates an expected call of GetUsersForFeed.
func (mr *MockUserRepositoryMockRecorder) GetUsersForFeed(userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersForFeed", reflect.TypeOf((*MockUserRepository)(nil).GetUsersForFeed), userID, limit, offset)
}

// Update mocks base method.
func (m *MockUserRepository) Update(user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), user)
}

// UpdateLastActive mocks base method.
func (m *MockUserRepository) UpdateLastActive(userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastActive", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastActive indicates an expected call of UpdateLastActive.
func (mr *MockUserRepositoryMockRecorder) UpdateLastActive(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastActive", reflect.TypeOf((*MockUserRepository)(nil).UpdateLastActive), userID)
}

// MockUserPhotoRepository is a mock of UserPhotoRepository interface.
type MockUserPhotoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserPhotoRepositoryMockRecorder
	isgomock struct{}
}

// MockUserPhotoRepositoryMockRecorder is the mock recorder for MockUserPhotoRepository.
type MockUserPhotoRepositoryMockRecorder struct {
	mock *MockUserPhotoRepository
}

// NewMockUserPhotoRepository creates a new mock instance.
func NewMockUserPhotoRepository(ctrl *gomock.Controller) *MockUserPhotoRepository {
	mock := &MockUserPhotoRepository{ctrl: ctrl}
	mock.recorder = &MockUserPhotoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserPhotoRepository) EXPECT() *MockUserPhotoRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserPhotoRepository) Create(photo *domain.UserPhoto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", photo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserPhotoRepositoryMockRecorder) Create(photo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserPhotoRepository)(nil).Create), photo)
}

// Delete mocks base method.
func (m *MockUserPhotoRepository) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserPhotoRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserPhotoRepository)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockUserPhotoRepository) GetByID(id uuid.UUID) (*domain.UserPhoto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*domain.UserPhoto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserPhotoRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserPhotoRepository)(nil).GetByID), id)
}

// GetByUserID mocks base method.
func (m *MockUserPhotoRepository) GetByUserID(userID uuid.UUID) ([]domain.UserPhoto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", userID)
	ret0, _ := ret[0].([]domain.UserPhoto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockUserPhotoRepositoryMockRecorder) GetByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockUserPhotoRepository)(nil).GetByUserID), userID)
}

// Update mocks base method.
func (m *MockUserPhotoRepository) Update(photo *domain.UserPhoto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", photo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserPhotoRepositoryMockRecorder) Update(photo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserPhotoRepository)(nil).Update), photo)
}

// UpdateDisplayOrder mocks base method.
func (m *MockUserPhotoRepository) UpdateDisplayOrder(userID uuid.UUID, photos []domain.UserPhoto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDisplayOrder", userID, photos)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDisplayOrder indicates an expected call of UpdateDisplayOrder.
func (mr *MockUserPhotoRepositoryMockRecorder) UpdateDisplayOrder(userID, photos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDisplayOrder", reflect.TypeOf((*MockUserPhotoRepository)(nil).UpdateDisplayOrder), userID, photos)
}

// MockUserPreferenceRepository is a mock of UserPreferenceRepository interface.
type MockUserPreferenceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserPreferenceRepositoryMockRecorder
	isgomock struct{}
}

// MockUserPreferenceRepositoryMockRecorder is the mock recorder for MockUserPreferenceRepository.
type MockUserPreferenceRepositoryMockRecorder struct {
	mock *MockUserPreferenceRepository
}

// NewMockUserPreferenceRepository creates a new mock instance.
func NewMockUserPreferenceRepository(ctrl *gomock.Controller) *MockUserPreferenceRepository {
	mock := &MockUserPreferenceRepository{ctrl: ctrl}
	mock.recorder = &MockUserPreferenceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserPreferenceRepository) EXPECT() *MockUserPreferenceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserPreferenceRepository) Create(preference *domain.UserPreference) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", preference)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserPreferenceRepositoryMockRecorder) Create(preference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserPreferenceRepository)(nil).Create), preference)
}

// Delete mocks base method.
func (m *MockUserPreferenceRepository) Delete(userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserPreferenceRepositoryMockRecorder) Delete(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserPreferenceRepository)(nil).Delete), userID)
}

// GetByUserID mocks base method.
func (m *MockUserPreferenceRepository) GetByUserID(userID uuid.UUID) (*domain.UserPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", userID)
	ret0, _ := ret[0].(*domain.UserPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockUserPreferenceRepositoryMockRecorder) GetByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockUserPreferenceRepository)(nil).GetByUserID), userID)
}

// Update mocks base method.
func (m *MockUserPreferenceRepository) Update(preference *domain.UserPreference) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", preference)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserPreferenceRepositoryMockRecorder) Update(preference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserPreferenceRepository)(nil).Update), preference)
}
