// Code generated by MockGen. DO NOT EDIT.
// Source: proto/core/core_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=proto/core/core_grpc.pb.go -destination=tests/mocks/core_grpc_client_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	core "github.com/go-park-mail-ru/2025_2_RoadTo200/backend/proto/core"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockCoreServiceClient is a mock of CoreServiceClient interface.
type MockCoreServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCoreServiceClientMockRecorder
	isgomock struct{}
}

// MockCoreServiceClientMockRecorder is the mock recorder for MockCoreServiceClient.
type MockCoreServiceClientMockRecorder struct {
	mock *MockCoreServiceClient
}

// NewMockCoreServiceClient creates a new mock instance.
func NewMockCoreServiceClient(ctrl *gomock.Controller) *MockCoreServiceClient {
	mock := &MockCoreServiceClient{ctrl: ctrl}
	mock.recorder = &MockCoreServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoreServiceClient) EXPECT() *MockCoreServiceClientMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockCoreServiceClient) ChangePassword(ctx context.Context, in *core.ChangePasswordRequest, opts ...grpc.CallOption) (*core.ChangePasswordResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ChangePassword", varargs...)
	ret0, _ := ret[0].(*core.ChangePasswordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockCoreServiceClientMockRecorder) ChangePassword(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockCoreServiceClient)(nil).ChangePassword), varargs...)
}

// CreateReport mocks base method.
func (m *MockCoreServiceClient) CreateReport(ctx context.Context, in *core.CreateReportRequest, opts ...grpc.CallOption) (*core.CreateReportResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateReport", varargs...)
	ret0, _ := ret[0].(*core.CreateReportResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReport indicates an expected call of CreateReport.
func (mr *MockCoreServiceClientMockRecorder) CreateReport(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReport", reflect.TypeOf((*MockCoreServiceClient)(nil).CreateReport), varargs...)
}

// CreateStrike mocks base method.
func (m *MockCoreServiceClient) CreateStrike(ctx context.Context, in *core.CreateStrikeRequest, opts ...grpc.CallOption) (*core.CreateStrikeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateStrike", varargs...)
	ret0, _ := ret[0].(*core.CreateStrikeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStrike indicates an expected call of CreateStrike.
func (mr *MockCoreServiceClientMockRecorder) CreateStrike(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStrike", reflect.TypeOf((*MockCoreServiceClient)(nil).CreateStrike), varargs...)
}

// DeleteAccount mocks base method.
func (m *MockCoreServiceClient) DeleteAccount(ctx context.Context, in *core.DeleteAccountRequest, opts ...grpc.CallOption) (*core.DeleteAccountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteAccount", varargs...)
	ret0, _ := ret[0].(*core.DeleteAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockCoreServiceClientMockRecorder) DeleteAccount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockCoreServiceClient)(nil).DeleteAccount), varargs...)
}

// DeletePhoto mocks base method.
func (m *MockCoreServiceClient) DeletePhoto(ctx context.Context, in *core.DeletePhotoRequest, opts ...grpc.CallOption) (*core.DeletePhotoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeletePhoto", varargs...)
	ret0, _ := ret[0].(*core.DeletePhotoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePhoto indicates an expected call of DeletePhoto.
func (mr *MockCoreServiceClientMockRecorder) DeletePhoto(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePhoto", reflect.TypeOf((*MockCoreServiceClient)(nil).DeletePhoto), varargs...)
}

// DeleteStrike mocks base method.
func (m *MockCoreServiceClient) DeleteStrike(ctx context.Context, in *core.DeleteStrikeRequest, opts ...grpc.CallOption) (*core.DeleteStrikeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteStrike", varargs...)
	ret0, _ := ret[0].(*core.DeleteStrikeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteStrike indicates an expected call of DeleteStrike.
func (mr *MockCoreServiceClientMockRecorder) DeleteStrike(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStrike", reflect.TypeOf((*MockCoreServiceClient)(nil).DeleteStrike), varargs...)
}

// GetFeed mocks base method.
func (m *MockCoreServiceClient) GetFeed(ctx context.Context, in *core.GetFeedRequest, opts ...grpc.CallOption) (*core.GetFeedResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFeed", varargs...)
	ret0, _ := ret[0].(*core.GetFeedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeed indicates an expected call of GetFeed.
func (mr *MockCoreServiceClientMockRecorder) GetFeed(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeed", reflect.TypeOf((*MockCoreServiceClient)(nil).GetFeed), varargs...)
}

// GetProfile mocks base method.
func (m *MockCoreServiceClient) GetProfile(ctx context.Context, in *core.GetProfileRequest, opts ...grpc.CallOption) (*core.GetProfileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProfile", varargs...)
	ret0, _ := ret[0].(*core.GetProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockCoreServiceClientMockRecorder) GetProfile(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockCoreServiceClient)(nil).GetProfile), varargs...)
}

// GetProfileWithRelations mocks base method.
func (m *MockCoreServiceClient) GetProfileWithRelations(ctx context.Context, in *core.GetProfileWithRelationsRequest, opts ...grpc.CallOption) (*core.GetProfileResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProfileWithRelations", varargs...)
	ret0, _ := ret[0].(*core.GetProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileWithRelations indicates an expected call of GetProfileWithRelations.
func (mr *MockCoreServiceClientMockRecorder) GetProfileWithRelations(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileWithRelations", reflect.TypeOf((*MockCoreServiceClient)(nil).GetProfileWithRelations), varargs...)
}

// GetStrike mocks base method.
func (m *MockCoreServiceClient) GetStrike(ctx context.Context, in *core.GetStrikeRequest, opts ...grpc.CallOption) (*core.GetStrikeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStrike", varargs...)
	ret0, _ := ret[0].(*core.GetStrikeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStrike indicates an expected call of GetStrike.
func (mr *MockCoreServiceClientMockRecorder) GetStrike(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStrike", reflect.TypeOf((*MockCoreServiceClient)(nil).GetStrike), varargs...)
}

// GetStrikesByDateRange mocks base method.
func (m *MockCoreServiceClient) GetStrikesByDateRange(ctx context.Context, in *core.GetStrikesByDateRangeRequest, opts ...grpc.CallOption) (*core.GetStrikesByDateRangeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStrikesByDateRange", varargs...)
	ret0, _ := ret[0].(*core.GetStrikesByDateRangeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStrikesByDateRange indicates an expected call of GetStrikesByDateRange.
func (mr *MockCoreServiceClientMockRecorder) GetStrikesByDateRange(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStrikesByDateRange", reflect.TypeOf((*MockCoreServiceClient)(nil).GetStrikesByDateRange), varargs...)
}

// GetStrikesByType mocks base method.
func (m *MockCoreServiceClient) GetStrikesByType(ctx context.Context, in *core.GetStrikesByTypeRequest, opts ...grpc.CallOption) (*core.GetStrikesByTypeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStrikesByType", varargs...)
	ret0, _ := ret[0].(*core.GetStrikesByTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStrikesByType indicates an expected call of GetStrikesByType.
func (mr *MockCoreServiceClientMockRecorder) GetStrikesByType(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStrikesByType", reflect.TypeOf((*MockCoreServiceClient)(nil).GetStrikesByType), varargs...)
}

// GetStrikesByUserID mocks base method.
func (m *MockCoreServiceClient) GetStrikesByUserID(ctx context.Context, in *core.GetStrikesByUserIDRequest, opts ...grpc.CallOption) (*core.GetStrikesByUserIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetStrikesByUserID", varargs...)
	ret0, _ := ret[0].(*core.GetStrikesByUserIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStrikesByUserID indicates an expected call of GetStrikesByUserID.
func (mr *MockCoreServiceClientMockRecorder) GetStrikesByUserID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStrikesByUserID", reflect.TypeOf((*MockCoreServiceClient)(nil).GetStrikesByUserID), varargs...)
}

// GetSupportStats mocks base method.
func (m *MockCoreServiceClient) GetSupportStats(ctx context.Context, in *core.GetSupportStatsRequest, opts ...grpc.CallOption) (*core.GetSupportStatsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSupportStats", varargs...)
	ret0, _ := ret[0].(*core.GetSupportStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupportStats indicates an expected call of GetSupportStats.
func (mr *MockCoreServiceClientMockRecorder) GetSupportStats(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportStats", reflect.TypeOf((*MockCoreServiceClient)(nil).GetSupportStats), varargs...)
}

// GetUserMatches mocks base method.
func (m *MockCoreServiceClient) GetUserMatches(ctx context.Context, in *core.GetUserMatchesRequest, opts ...grpc.CallOption) (*core.GetUserMatchesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserMatches", varargs...)
	ret0, _ := ret[0].(*core.GetUserMatchesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserMatches indicates an expected call of GetUserMatches.
func (mr *MockCoreServiceClientMockRecorder) GetUserMatches(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserMatches", reflect.TypeOf((*MockCoreServiceClient)(nil).GetUserMatches), varargs...)
}

// GetUserReport mocks base method.
func (m *MockCoreServiceClient) GetUserReport(ctx context.Context, in *core.GetUserReportRequest, opts ...grpc.CallOption) (*core.GetUserReportResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserReport", varargs...)
	ret0, _ := ret[0].(*core.GetUserReportResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserReport indicates an expected call of GetUserReport.
func (mr *MockCoreServiceClientMockRecorder) GetUserReport(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserReport", reflect.TypeOf((*MockCoreServiceClient)(nil).GetUserReport), varargs...)
}

// GetUserReports mocks base method.
func (m *MockCoreServiceClient) GetUserReports(ctx context.Context, in *core.GetUserReportsRequest, opts ...grpc.CallOption) (*core.GetUserReportsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserReports", varargs...)
	ret0, _ := ret[0].(*core.GetUserReportsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserReports indicates an expected call of GetUserReports.
func (mr *MockCoreServiceClientMockRecorder) GetUserReports(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserReports", reflect.TypeOf((*MockCoreServiceClient)(nil).GetUserReports), varargs...)
}

// GetUserStrikeStats mocks base method.
func (m *MockCoreServiceClient) GetUserStrikeStats(ctx context.Context, in *core.GetUserStrikeStatsRequest, opts ...grpc.CallOption) (*core.GetUserStrikeStatsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserStrikeStats", varargs...)
	ret0, _ := ret[0].(*core.GetUserStrikeStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStrikeStats indicates an expected call of GetUserStrikeStats.
func (mr *MockCoreServiceClientMockRecorder) GetUserStrikeStats(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStrikeStats", reflect.TypeOf((*MockCoreServiceClient)(nil).GetUserStrikeStats), varargs...)
}

// ProcessSwipe mocks base method.
func (m *MockCoreServiceClient) ProcessSwipe(ctx context.Context, in *core.ProcessSwipeRequest, opts ...grpc.CallOption) (*core.ProcessSwipeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ProcessSwipe", varargs...)
	ret0, _ := ret[0].(*core.ProcessSwipeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessSwipe indicates an expected call of ProcessSwipe.
func (mr *MockCoreServiceClientMockRecorder) ProcessSwipe(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessSwipe", reflect.TypeOf((*MockCoreServiceClient)(nil).ProcessSwipe), varargs...)
}

// ReorderPhotos mocks base method.
func (m *MockCoreServiceClient) ReorderPhotos(ctx context.Context, in *core.ReorderPhotosRequest, opts ...grpc.CallOption) (*core.ReorderPhotosResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReorderPhotos", varargs...)
	ret0, _ := ret[0].(*core.ReorderPhotosResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReorderPhotos indicates an expected call of ReorderPhotos.
func (mr *MockCoreServiceClientMockRecorder) ReorderPhotos(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderPhotos", reflect.TypeOf((*MockCoreServiceClient)(nil).ReorderPhotos), varargs...)
}

// SetPrimaryPhoto mocks base method.
func (m *MockCoreServiceClient) SetPrimaryPhoto(ctx context.Context, in *core.SetPrimaryPhotoRequest, opts ...grpc.CallOption) (*core.SetPrimaryPhotoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetPrimaryPhoto", varargs...)
	ret0, _ := ret[0].(*core.SetPrimaryPhotoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPrimaryPhoto indicates an expected call of SetPrimaryPhoto.
func (mr *MockCoreServiceClientMockRecorder) SetPrimaryPhoto(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrimaryPhoto", reflect.TypeOf((*MockCoreServiceClient)(nil).SetPrimaryPhoto), varargs...)
}

// Unmatch mocks base method.
func (m *MockCoreServiceClient) Unmatch(ctx context.Context, in *core.UnmatchRequest, opts ...grpc.CallOption) (*core.UnmatchResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Unmatch", varargs...)
	ret0, _ := ret[0].(*core.UnmatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unmatch indicates an expected call of Unmatch.
func (mr *MockCoreServiceClientMockRecorder) Unmatch(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmatch", reflect.TypeOf((*MockCoreServiceClient)(nil).Unmatch), varargs...)
}

// UpdateInterests mocks base method.
func (m *MockCoreServiceClient) UpdateInterests(ctx context.Context, in *core.UpdateInterestsRequest, opts ...grpc.CallOption) (*core.UpdateInterestsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateInterests", varargs...)
	ret0, _ := ret[0].(*core.UpdateInterestsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInterests indicates an expected call of UpdateInterests.
func (mr *MockCoreServiceClientMockRecorder) UpdateInterests(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInterests", reflect.TypeOf((*MockCoreServiceClient)(nil).UpdateInterests), varargs...)
}

// UpdatePreferences mocks base method.
func (m *MockCoreServiceClient) UpdatePreferences(ctx context.Context, in *core.UpdatePreferencesRequest, opts ...grpc.CallOption) (*core.UpdatePreferencesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdatePreferences", varargs...)
	ret0, _ := ret[0].(*core.UpdatePreferencesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePreferences indicates an expected call of UpdatePreferences.
func (mr *MockCoreServiceClientMockRecorder) UpdatePreferences(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePreferences", reflect.TypeOf((*MockCoreServiceClient)(nil).UpdatePreferences), varargs...)
}

// UpdateProfileInfo mocks base method.
func (m *MockCoreServiceClient) UpdateProfileInfo(ctx context.Context, in *core.UpdateProfileInfoRequest, opts ...grpc.CallOption) (*core.UpdateProfileInfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateProfileInfo", varargs...)
	ret0, _ := ret[0].(*core.UpdateProfileInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfileInfo indicates an expected call of UpdateProfileInfo.
func (mr *MockCoreServiceClientMockRecorder) UpdateProfileInfo(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfileInfo", reflect.TypeOf((*MockCoreServiceClient)(nil).UpdateProfileInfo), varargs...)
}

// UpdateStrikeStatus mocks base method.
func (m *MockCoreServiceClient) UpdateStrikeStatus(ctx context.Context, in *core.UpdateStrikeStatusRequest, opts ...grpc.CallOption) (*core.UpdateStrikeStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateStrikeStatus", varargs...)
	ret0, _ := ret[0].(*core.UpdateStrikeStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStrikeStatus indicates an expected call of UpdateStrikeStatus.
func (mr *MockCoreServiceClientMockRecorder) UpdateStrikeStatus(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStrikeStatus", reflect.TypeOf((*MockCoreServiceClient)(nil).UpdateStrikeStatus), varargs...)
}

// UploadPhoto mocks base method.
func (m *MockCoreServiceClient) UploadPhoto(ctx context.Context, in *core.UploadPhotoRequest, opts ...grpc.CallOption) (*core.UploadPhotoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UploadPhoto", varargs...)
	ret0, _ := ret[0].(*core.UploadPhotoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPhoto indicates an expected call of UploadPhoto.
func (mr *MockCoreServiceClientMockRecorder) UploadPhoto(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPhoto", reflect.TypeOf((*MockCoreServiceClient)(nil).UploadPhoto), varargs...)
}

// MockCoreServiceServer is a mock of CoreServiceServer interface.
type MockCoreServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockCoreServiceServerMockRecorder
	isgomock struct{}
}

// MockCoreServiceServerMockRecorder is the mock recorder for MockCoreServiceServer.
type MockCoreServiceServerMockRecorder struct {
	mock *MockCoreServiceServer
}

// NewMockCoreServiceServer creates a new mock instance.
func NewMockCoreServiceServer(ctrl *gomock.Controller) *MockCoreServiceServer {
	mock := &MockCoreServiceServer{ctrl: ctrl}
	mock.recorder = &MockCoreServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoreServiceServer) EXPECT() *MockCoreServiceServerMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockCoreServiceServer) ChangePassword(arg0 context.Context, arg1 *core.ChangePasswordRequest) (*core.ChangePasswordResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", arg0, arg1)
	ret0, _ := ret[0].(*core.ChangePasswordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockCoreServiceServerMockRecorder) ChangePassword(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockCoreServiceServer)(nil).ChangePassword), arg0, arg1)
}

// CreateReport mocks base method.
func (m *MockCoreServiceServer) CreateReport(arg0 context.Context, arg1 *core.CreateReportRequest) (*core.CreateReportResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReport", arg0, arg1)
	ret0, _ := ret[0].(*core.CreateReportResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReport indicates an expected call of CreateReport.
func (mr *MockCoreServiceServerMockRecorder) CreateReport(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReport", reflect.TypeOf((*MockCoreServiceServer)(nil).CreateReport), arg0, arg1)
}

// CreateStrike mocks base method.
func (m *MockCoreServiceServer) CreateStrike(arg0 context.Context, arg1 *core.CreateStrikeRequest) (*core.CreateStrikeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStrike", arg0, arg1)
	ret0, _ := ret[0].(*core.CreateStrikeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStrike indicates an expected call of CreateStrike.
func (mr *MockCoreServiceServerMockRecorder) CreateStrike(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStrike", reflect.TypeOf((*MockCoreServiceServer)(nil).CreateStrike), arg0, arg1)
}

// DeleteAccount mocks base method.
func (m *MockCoreServiceServer) DeleteAccount(arg0 context.Context, arg1 *core.DeleteAccountRequest) (*core.DeleteAccountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", arg0, arg1)
	ret0, _ := ret[0].(*core.DeleteAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockCoreServiceServerMockRecorder) DeleteAccount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockCoreServiceServer)(nil).DeleteAccount), arg0, arg1)
}

// DeletePhoto mocks base method.
func (m *MockCoreServiceServer) DeletePhoto(arg0 context.Context, arg1 *core.DeletePhotoRequest) (*core.DeletePhotoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePhoto", arg0, arg1)
	ret0, _ := ret[0].(*core.DeletePhotoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePhoto indicates an expected call of DeletePhoto.
func (mr *MockCoreServiceServerMockRecorder) DeletePhoto(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePhoto", reflect.TypeOf((*MockCoreServiceServer)(nil).DeletePhoto), arg0, arg1)
}

// DeleteStrike mocks base method.
func (m *MockCoreServiceServer) DeleteStrike(arg0 context.Context, arg1 *core.DeleteStrikeRequest) (*core.DeleteStrikeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStrike", arg0, arg1)
	ret0, _ := ret[0].(*core.DeleteStrikeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteStrike indicates an expected call of DeleteStrike.
func (mr *MockCoreServiceServerMockRecorder) DeleteStrike(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStrike", reflect.TypeOf((*MockCoreServiceServer)(nil).DeleteStrike), arg0, arg1)
}

// GetFeed mocks base method.
func (m *MockCoreServiceServer) GetFeed(arg0 context.Context, arg1 *core.GetFeedRequest) (*core.GetFeedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeed", arg0, arg1)
	ret0, _ := ret[0].(*core.GetFeedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeed indicates an expected call of GetFeed.
func (mr *MockCoreServiceServerMockRecorder) GetFeed(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeed", reflect.TypeOf((*MockCoreServiceServer)(nil).GetFeed), arg0, arg1)
}

// GetProfile mocks base method.
func (m *MockCoreServiceServer) GetProfile(arg0 context.Context, arg1 *core.GetProfileRequest) (*core.GetProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", arg0, arg1)
	ret0, _ := ret[0].(*core.GetProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockCoreServiceServerMockRecorder) GetProfile(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockCoreServiceServer)(nil).GetProfile), arg0, arg1)
}

// GetProfileWithRelations mocks base method.
func (m *MockCoreServiceServer) GetProfileWithRelations(arg0 context.Context, arg1 *core.GetProfileWithRelationsRequest) (*core.GetProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileWithRelations", arg0, arg1)
	ret0, _ := ret[0].(*core.GetProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileWithRelations indicates an expected call of GetProfileWithRelations.
func (mr *MockCoreServiceServerMockRecorder) GetProfileWithRelations(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileWithRelations", reflect.TypeOf((*MockCoreServiceServer)(nil).GetProfileWithRelations), arg0, arg1)
}

// GetStrike mocks base method.
func (m *MockCoreServiceServer) GetStrike(arg0 context.Context, arg1 *core.GetStrikeRequest) (*core.GetStrikeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStrike", arg0, arg1)
	ret0, _ := ret[0].(*core.GetStrikeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStrike indicates an expected call of GetStrike.
func (mr *MockCoreServiceServerMockRecorder) GetStrike(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStrike", reflect.TypeOf((*MockCoreServiceServer)(nil).GetStrike), arg0, arg1)
}

// GetStrikesByDateRange mocks base method.
func (m *MockCoreServiceServer) GetStrikesByDateRange(arg0 context.Context, arg1 *core.GetStrikesByDateRangeRequest) (*core.GetStrikesByDateRangeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStrikesByDateRange", arg0, arg1)
	ret0, _ := ret[0].(*core.GetStrikesByDateRangeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStrikesByDateRange indicates an expected call of GetStrikesByDateRange.
func (mr *MockCoreServiceServerMockRecorder) GetStrikesByDateRange(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStrikesByDateRange", reflect.TypeOf((*MockCoreServiceServer)(nil).GetStrikesByDateRange), arg0, arg1)
}

// GetStrikesByType mocks base method.
func (m *MockCoreServiceServer) GetStrikesByType(arg0 context.Context, arg1 *core.GetStrikesByTypeRequest) (*core.GetStrikesByTypeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStrikesByType", arg0, arg1)
	ret0, _ := ret[0].(*core.GetStrikesByTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStrikesByType indicates an expected call of GetStrikesByType.
func (mr *MockCoreServiceServerMockRecorder) GetStrikesByType(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStrikesByType", reflect.TypeOf((*MockCoreServiceServer)(nil).GetStrikesByType), arg0, arg1)
}

// GetStrikesByUserID mocks base method.
func (m *MockCoreServiceServer) GetStrikesByUserID(arg0 context.Context, arg1 *core.GetStrikesByUserIDRequest) (*core.GetStrikesByUserIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStrikesByUserID", arg0, arg1)
	ret0, _ := ret[0].(*core.GetStrikesByUserIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStrikesByUserID indicates an expected call of GetStrikesByUserID.
func (mr *MockCoreServiceServerMockRecorder) GetStrikesByUserID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStrikesByUserID", reflect.TypeOf((*MockCoreServiceServer)(nil).GetStrikesByUserID), arg0, arg1)
}

// GetSupportStats mocks base method.
func (m *MockCoreServiceServer) GetSupportStats(arg0 context.Context, arg1 *core.GetSupportStatsRequest) (*core.GetSupportStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupportStats", arg0, arg1)
	ret0, _ := ret[0].(*core.GetSupportStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupportStats indicates an expected call of GetSupportStats.
func (mr *MockCoreServiceServerMockRecorder) GetSupportStats(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportStats", reflect.TypeOf((*MockCoreServiceServer)(nil).GetSupportStats), arg0, arg1)
}

// GetUserMatches mocks base method.
func (m *MockCoreServiceServer) GetUserMatches(arg0 context.Context, arg1 *core.GetUserMatchesRequest) (*core.GetUserMatchesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserMatches", arg0, arg1)
	ret0, _ := ret[0].(*core.GetUserMatchesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserMatches indicates an expected call of GetUserMatches.
func (mr *MockCoreServiceServerMockRecorder) GetUserMatches(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserMatches", reflect.TypeOf((*MockCoreServiceServer)(nil).GetUserMatches), arg0, arg1)
}

// GetUserReport mocks base method.
func (m *MockCoreServiceServer) GetUserReport(arg0 context.Context, arg1 *core.GetUserReportRequest) (*core.GetUserReportResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserReport", arg0, arg1)
	ret0, _ := ret[0].(*core.GetUserReportResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserReport indicates an expected call of GetUserReport.
func (mr *MockCoreServiceServerMockRecorder) GetUserReport(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserReport", reflect.TypeOf((*MockCoreServiceServer)(nil).GetUserReport), arg0, arg1)
}

// GetUserReports mocks base method.
func (m *MockCoreServiceServer) GetUserReports(arg0 context.Context, arg1 *core.GetUserReportsRequest) (*core.GetUserReportsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserReports", arg0, arg1)
	ret0, _ := ret[0].(*core.GetUserReportsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserReports indicates an expected call of GetUserReports.
func (mr *MockCoreServiceServerMockRecorder) GetUserReports(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserReports", reflect.TypeOf((*MockCoreServiceServer)(nil).GetUserReports), arg0, arg1)
}

// GetUserStrikeStats mocks base method.
func (m *MockCoreServiceServer) GetUserStrikeStats(arg0 context.Context, arg1 *core.GetUserStrikeStatsRequest) (*core.GetUserStrikeStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStrikeStats", arg0, arg1)
	ret0, _ := ret[0].(*core.GetUserStrikeStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStrikeStats indicates an expected call of GetUserStrikeStats.
func (mr *MockCoreServiceServerMockRecorder) GetUserStrikeStats(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStrikeStats", reflect.TypeOf((*MockCoreServiceServer)(nil).GetUserStrikeStats), arg0, arg1)
}

// ProcessSwipe mocks base method.
func (m *MockCoreServiceServer) ProcessSwipe(arg0 context.Context, arg1 *core.ProcessSwipeRequest) (*core.ProcessSwipeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessSwipe", arg0, arg1)
	ret0, _ := ret[0].(*core.ProcessSwipeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessSwipe indicates an expected call of ProcessSwipe.
func (mr *MockCoreServiceServerMockRecorder) ProcessSwipe(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessSwipe", reflect.TypeOf((*MockCoreServiceServer)(nil).ProcessSwipe), arg0, arg1)
}

// ReorderPhotos mocks base method.
func (m *MockCoreServiceServer) ReorderPhotos(arg0 context.Context, arg1 *core.ReorderPhotosRequest) (*core.ReorderPhotosResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderPhotos", arg0, arg1)
	ret0, _ := ret[0].(*core.ReorderPhotosResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReorderPhotos indicates an expected call of ReorderPhotos.
func (mr *MockCoreServiceServerMockRecorder) ReorderPhotos(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderPhotos", reflect.TypeOf((*MockCoreServiceServer)(nil).ReorderPhotos), arg0, arg1)
}

// SetPrimaryPhoto mocks base method.
func (m *MockCoreServiceServer) SetPrimaryPhoto(arg0 context.Context, arg1 *core.SetPrimaryPhotoRequest) (*core.SetPrimaryPhotoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrimaryPhoto", arg0, arg1)
	ret0, _ := ret[0].(*core.SetPrimaryPhotoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPrimaryPhoto indicates an expected call of SetPrimaryPhoto.
func (mr *MockCoreServiceServerMockRecorder) SetPrimaryPhoto(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrimaryPhoto", reflect.TypeOf((*MockCoreServiceServer)(nil).SetPrimaryPhoto), arg0, arg1)
}

// Unmatch mocks base method.
func (m *MockCoreServiceServer) Unmatch(arg0 context.Context, arg1 *core.UnmatchRequest) (*core.UnmatchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmatch", arg0, arg1)
	ret0, _ := ret[0].(*core.UnmatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unmatch indicates an expected call of Unmatch.
func (mr *MockCoreServiceServerMockRecorder) Unmatch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmatch", reflect.TypeOf((*MockCoreServiceServer)(nil).Unmatch), arg0, arg1)
}

// UpdateInterests mocks base method.
func (m *MockCoreServiceServer) UpdateInterests(arg0 context.Context, arg1 *core.UpdateInterestsRequest) (*core.UpdateInterestsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInterests", arg0, arg1)
	ret0, _ := ret[0].(*core.UpdateInterestsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInterests indicates an expected call of UpdateInterests.
func (mr *MockCoreServiceServerMockRecorder) UpdateInterests(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInterests", reflect.TypeOf((*MockCoreServiceServer)(nil).UpdateInterests), arg0, arg1)
}

// UpdatePreferences mocks base method.
func (m *MockCoreServiceServer) UpdatePreferences(arg0 context.Context, arg1 *core.UpdatePreferencesRequest) (*core.UpdatePreferencesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePreferences", arg0, arg1)
	ret0, _ := ret[0].(*core.UpdatePreferencesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePreferences indicates an expected call of UpdatePreferences.
func (mr *MockCoreServiceServerMockRecorder) UpdatePreferences(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePreferences", reflect.TypeOf((*MockCoreServiceServer)(nil).UpdatePreferences), arg0, arg1)
}

// UpdateProfileInfo mocks base method.
func (m *MockCoreServiceServer) UpdateProfileInfo(arg0 context.Context, arg1 *core.UpdateProfileInfoRequest) (*core.UpdateProfileInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfileInfo", arg0, arg1)
	ret0, _ := ret[0].(*core.UpdateProfileInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfileInfo indicates an expected call of UpdateProfileInfo.
func (mr *MockCoreServiceServerMockRecorder) UpdateProfileInfo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfileInfo", reflect.TypeOf((*MockCoreServiceServer)(nil).UpdateProfileInfo), arg0, arg1)
}

// UpdateStrikeStatus mocks base method.
func (m *MockCoreServiceServer) UpdateStrikeStatus(arg0 context.Context, arg1 *core.UpdateStrikeStatusRequest) (*core.UpdateStrikeStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStrikeStatus", arg0, arg1)
	ret0, _ := ret[0].(*core.UpdateStrikeStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStrikeStatus indicates an expected call of UpdateStrikeStatus.
func (mr *MockCoreServiceServerMockRecorder) UpdateStrikeStatus(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStrikeStatus", reflect.TypeOf((*MockCoreServiceServer)(nil).UpdateStrikeStatus), arg0, arg1)
}

// UploadPhoto mocks base method.
func (m *MockCoreServiceServer) UploadPhoto(arg0 context.Context, arg1 *core.UploadPhotoRequest) (*core.UploadPhotoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPhoto", arg0, arg1)
	ret0, _ := ret[0].(*core.UploadPhotoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPhoto indicates an expected call of UploadPhoto.
func (mr *MockCoreServiceServerMockRecorder) UploadPhoto(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPhoto", reflect.TypeOf((*MockCoreServiceServer)(nil).UploadPhoto), arg0, arg1)
}

// mustEmbedUnimplementedCoreServiceServer mocks base method.
func (m *MockCoreServiceServer) mustEmbedUnimplementedCoreServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedCoreServiceServer")
}

// mustEmbedUnimplementedCoreServiceServer indicates an expected call of mustEmbedUnimplementedCoreServiceServer.
func (mr *MockCoreServiceServerMockRecorder) mustEmbedUnimplementedCoreServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedCoreServiceServer", reflect.TypeOf((*MockCoreServiceServer)(nil).mustEmbedUnimplementedCoreServiceServer))
}

// MockUnsafeCoreServiceServer is a mock of UnsafeCoreServiceServer interface.
type MockUnsafeCoreServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeCoreServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeCoreServiceServerMockRecorder is the mock recorder for MockUnsafeCoreServiceServer.
type MockUnsafeCoreServiceServerMockRecorder struct {
	mock *MockUnsafeCoreServiceServer
}

// NewMockUnsafeCoreServiceServer creates a new mock instance.
func NewMockUnsafeCoreServiceServer(ctrl *gomock.Controller) *MockUnsafeCoreServiceServer {
	mock := &MockUnsafeCoreServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeCoreServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeCoreServiceServer) EXPECT() *MockUnsafeCoreServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedCoreServiceServer mocks base method.
func (m *MockUnsafeCoreServiceServer) mustEmbedUnimplementedCoreServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedCoreServiceServer")
}

// mustEmbedUnimplementedCoreServiceServer indicates an expected call of mustEmbedUnimplementedCoreServiceServer.
func (mr *MockUnsafeCoreServiceServerMockRecorder) mustEmbedUnimplementedCoreServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedCoreServiceServer", reflect.TypeOf((*MockUnsafeCoreServiceServer)(nil).mustEmbedUnimplementedCoreServiceServer))
}
