// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/interfaces/feed_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/interfaces/feed_service.go -destination=tests/mocks/feed_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	"github.com/go-park-mail-ru/2025_2_RoadTo200/backend/internal/handler/dto"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockFeedService is a mock of FeedService interface.
type MockFeedService struct {
	ctrl     *gomock.Controller
	recorder *MockFeedServiceMockRecorder
	isgomock struct{}
}

// MockFeedServiceMockRecorder is the mock recorder for MockFeedService.
type MockFeedServiceMockRecorder struct {
	mock *MockFeedService
}

// NewMockFeedService creates a new mock instance.
func NewMockFeedService(ctrl *gomock.Controller) *MockFeedService {
	mock := &MockFeedService{ctrl: ctrl}
	mock.recorder = &MockFeedServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedService) EXPECT() *MockFeedServiceMockRecorder {
	return m.recorder
}

// GetFeed mocks base method.
func (m *MockFeedService) GetFeed(ctx context.Context, userID uuid.UUID, limit, offset int) ([]dto.FeedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeed", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]dto.FeedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeed indicates an expected call of GetFeed.
func (mr *MockFeedServiceMockRecorder) GetFeed(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeed", reflect.TypeOf((*MockFeedService)(nil).GetFeed), ctx, userID, limit, offset)
}
