// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/interfaces/match_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/interfaces/match_service.go -destination=tests/mocks/match_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	"github.com/go-park-mail-ru/2025_2_RoadTo200/backend/internal/handler/dto"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchService is a mock of MatchService interface.
type MockMatchService struct {
	ctrl     *gomock.Controller
	recorder *MockMatchServiceMockRecorder
	isgomock struct{}
}

// MockMatchServiceMockRecorder is the mock recorder for MockMatchService.
type MockMatchServiceMockRecorder struct {
	mock *MockMatchService
}

// NewMockMatchService creates a new mock instance.
func NewMockMatchService(ctrl *gomock.Controller) *MockMatchService {
	mock := &MockMatchService{ctrl: ctrl}
	mock.recorder = &MockMatchServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchService) EXPECT() *MockMatchServiceMockRecorder {
	return m.recorder
}

// GetUserMatches mocks base method.
func (m *MockMatchService) GetUserMatches(ctx context.Context, userID uuid.UUID, limit, offset int) (*dto.MatchesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserMatches", ctx, userID, limit, offset)
	ret0, _ := ret[0].(*dto.MatchesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserMatches indicates an expected call of GetUserMatches.
func (mr *MockMatchServiceMockRecorder) GetUserMatches(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserMatches", reflect.TypeOf((*MockMatchService)(nil).GetUserMatches), ctx, userID, limit, offset)
}

// Unmatch mocks base method.
func (m *MockMatchService) Unmatch(ctx context.Context, userID, targetUserID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmatch", ctx, userID, targetUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unmatch indicates an expected call of Unmatch.
func (mr *MockMatchServiceMockRecorder) Unmatch(ctx, userID, targetUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmatch", reflect.TypeOf((*MockMatchService)(nil).Unmatch), ctx, userID, targetUserID)
}
