// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces/storage_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/interfaces/storage_repository.go -destination=tests/mocks/match_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2025_2_RoadTo200/backend/internal/domain/entities"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchRepository is a mock of MatchRepository interface.
type MockMatchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMatchRepositoryMockRecorder
	isgomock struct{}
}

// MockMatchRepositoryMockRecorder is the mock recorder for MockMatchRepository.
type MockMatchRepositoryMockRecorder struct {
	mock *MockMatchRepository
}

// NewMockMatchRepository creates a new mock instance.
func NewMockMatchRepository(ctrl *gomock.Controller) *MockMatchRepository {
	mock := &MockMatchRepository{ctrl: ctrl}
	mock.recorder = &MockMatchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchRepository) EXPECT() *MockMatchRepositoryMockRecorder {
	return m.recorder
}

// CheckMutualLike mocks base method.
func (m *MockMatchRepository) CheckMutualLike(ctx context.Context, user1ID, user2ID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckMutualLike", ctx, user1ID, user2ID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckMutualLike indicates an expected call of CheckMutualLike.
func (mr *MockMatchRepositoryMockRecorder) CheckMutualLike(ctx, user1ID, user2ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckMutualLike", reflect.TypeOf((*MockMatchRepository)(nil).CheckMutualLike), ctx, user1ID, user2ID)
}

// Create mocks base method.
func (m *MockMatchRepository) Create(ctx context.Context, match *domain.Match) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, match)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMatchRepositoryMockRecorder) Create(ctx, match any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMatchRepository)(nil).Create), ctx, match)
}

// Delete mocks base method.
func (m *MockMatchRepository) Delete(ctx context.Context, user1ID, user2ID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, user1ID, user2ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMatchRepositoryMockRecorder) Delete(ctx, user1ID, user2ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMatchRepository)(nil).Delete), ctx, user1ID, user2ID)
}

// GetByID mocks base method.
func (m *MockMatchRepository) GetByID(ctx context.Context, matchID uuid.UUID) (*domain.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, matchID)
	ret0, _ := ret[0].(*domain.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMatchRepositoryMockRecorder) GetByID(ctx, matchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMatchRepository)(nil).GetByID), ctx, matchID)
}

// GetByUsers mocks base method.
func (m *MockMatchRepository) GetByUsers(ctx context.Context, user1ID, user2ID uuid.UUID) (*domain.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsers", ctx, user1ID, user2ID)
	ret0, _ := ret[0].(*domain.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsers indicates an expected call of GetByUsers.
func (mr *MockMatchRepositoryMockRecorder) GetByUsers(ctx, user1ID, user2ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsers", reflect.TypeOf((*MockMatchRepository)(nil).GetByUsers), ctx, user1ID, user2ID)
}

// GetUserMatches mocks base method.
func (m *MockMatchRepository) GetUserMatches(ctx context.Context, userID uuid.UUID, limit, offset int) ([]domain.Match, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserMatches", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]domain.Match)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserMatches indicates an expected call of GetUserMatches.
func (mr *MockMatchRepositoryMockRecorder) GetUserMatches(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserMatches", reflect.TypeOf((*MockMatchRepository)(nil).GetUserMatches), ctx, userID, limit, offset)
}

// UpdateActive mocks base method.
func (m *MockMatchRepository) UpdateActive(ctx context.Context, user1ID, user2ID uuid.UUID, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActive", ctx, user1ID, user2ID, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActive indicates an expected call of UpdateActive.
func (mr *MockMatchRepositoryMockRecorder) UpdateActive(ctx, user1ID, user2ID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActive", reflect.TypeOf((*MockMatchRepository)(nil).UpdateActive), ctx, user1ID, user2ID, isActive)
}
