// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/interfaces/payment_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/interfaces/payment_service.go -destination=tests/mocks/payment_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentService is a mock of PaymentService interface.
type MockPaymentService struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentServiceMockRecorder
	isgomock struct{}
}

// MockPaymentServiceMockRecorder is the mock recorder for MockPaymentService.
type MockPaymentServiceMockRecorder struct {
	mock *MockPaymentService
}

// NewMockPaymentService creates a new mock instance.
func NewMockPaymentService(ctrl *gomock.Controller) *MockPaymentService {
	mock := &MockPaymentService{ctrl: ctrl}
	mock.recorder = &MockPaymentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentService) EXPECT() *MockPaymentServiceMockRecorder {
	return m.recorder
}

// CreatePaymentLink mocks base method.
func (m *MockPaymentService) CreatePaymentLink(ctx context.Context, userID uuid.UUID, planID string, amount float64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePaymentLink", ctx, userID, planID, amount)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePaymentLink indicates an expected call of CreatePaymentLink.
func (mr *MockPaymentServiceMockRecorder) CreatePaymentLink(ctx, userID, planID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentLink", reflect.TypeOf((*MockPaymentService)(nil).CreatePaymentLink), ctx, userID, planID, amount)
}

// ProcessWebhook mocks base method.
func (m *MockPaymentService) ProcessWebhook(ctx context.Context, webhookData map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessWebhook", ctx, webhookData)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessWebhook indicates an expected call of ProcessWebhook.
func (mr *MockPaymentServiceMockRecorder) ProcessWebhook(ctx, webhookData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessWebhook", reflect.TypeOf((*MockPaymentService)(nil).ProcessWebhook), ctx, webhookData)
}
