// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/interfaces/profile_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/interfaces/profile_service.go -destination=tests/mocks/profile_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2025_2_RoadTo200/backend/internal/domain/entities"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockProfileService is a mock of ProfileService interface.
type MockProfileService struct {
	ctrl     *gomock.Controller
	recorder *MockProfileServiceMockRecorder
	isgomock struct{}
}

// MockProfileServiceMockRecorder is the mock recorder for MockProfileService.
type MockProfileServiceMockRecorder struct {
	mock *MockProfileService
}

// NewMockProfileService creates a new mock instance.
func NewMockProfileService(ctrl *gomock.Controller) *MockProfileService {
	mock := &MockProfileService{ctrl: ctrl}
	mock.recorder = &MockProfileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileService) EXPECT() *MockProfileServiceMockRecorder {
	return m.recorder
}

// DeletePhoto mocks base method.
func (m *MockProfileService) DeletePhoto(ctx context.Context, userID, photoID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePhoto", ctx, userID, photoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePhoto indicates an expected call of DeletePhoto.
func (mr *MockProfileServiceMockRecorder) DeletePhoto(ctx, userID, photoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePhoto", reflect.TypeOf((*MockProfileService)(nil).DeletePhoto), ctx, userID, photoID)
}

// GetProfile mocks base method.
func (m *MockProfileService) GetProfile(ctx context.Context, userID uuid.UUID) (*domain.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, userID)
	ret0, _ := ret[0].(*domain.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockProfileServiceMockRecorder) GetProfile(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockProfileService)(nil).GetProfile), ctx, userID)
}

// ReorderPhotos mocks base method.
func (m *MockProfileService) ReorderPhotos(ctx context.Context, userID uuid.UUID, photoIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderPhotos", ctx, userID, photoIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReorderPhotos indicates an expected call of ReorderPhotos.
func (mr *MockProfileServiceMockRecorder) ReorderPhotos(ctx, userID, photoIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderPhotos", reflect.TypeOf((*MockProfileService)(nil).ReorderPhotos), ctx, userID, photoIDs)
}

// SetPrimaryPhoto mocks base method.
func (m *MockProfileService) SetPrimaryPhoto(ctx context.Context, userID, photoID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrimaryPhoto", ctx, userID, photoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPrimaryPhoto indicates an expected call of SetPrimaryPhoto.
func (mr *MockProfileServiceMockRecorder) SetPrimaryPhoto(ctx, userID, photoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrimaryPhoto", reflect.TypeOf((*MockProfileService)(nil).SetPrimaryPhoto), ctx, userID, photoID)
}

// UpdateInterests mocks base method.
func (m *MockProfileService) UpdateInterests(ctx context.Context, userID uuid.UUID, interests []domain.Interest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInterests", ctx, userID, interests)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInterests indicates an expected call of UpdateInterests.
func (mr *MockProfileServiceMockRecorder) UpdateInterests(ctx, userID, interests any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInterests", reflect.TypeOf((*MockProfileService)(nil).UpdateInterests), ctx, userID, interests)
}

// UpdatePreferences mocks base method.
func (m *MockProfileService) UpdatePreferences(ctx context.Context, userID uuid.UUID, updateData *domain.PreferencesUpdateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePreferences", ctx, userID, updateData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePreferences indicates an expected call of UpdatePreferences.
func (mr *MockProfileServiceMockRecorder) UpdatePreferences(ctx, userID, updateData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePreferences", reflect.TypeOf((*MockProfileService)(nil).UpdatePreferences), ctx, userID, updateData)
}

// UpdateProfileInfo mocks base method.
func (m *MockProfileService) UpdateProfileInfo(ctx context.Context, userID uuid.UUID, updateData *domain.ProfileUpdateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfileInfo", ctx, userID, updateData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfileInfo indicates an expected call of UpdateProfileInfo.
func (mr *MockProfileServiceMockRecorder) UpdateProfileInfo(ctx, userID, updateData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfileInfo", reflect.TypeOf((*MockProfileService)(nil).UpdateProfileInfo), ctx, userID, updateData)
}

// UploadPhoto mocks base method.
func (m *MockProfileService) UploadPhoto(ctx context.Context, userID uuid.UUID, content []byte, contentType string) (*domain.UserPhoto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPhoto", ctx, userID, content, contentType)
	ret0, _ := ret[0].(*domain.UserPhoto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPhoto indicates an expected call of UploadPhoto.
func (mr *MockProfileServiceMockRecorder) UploadPhoto(ctx, userID, content, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPhoto", reflect.TypeOf((*MockProfileService)(nil).UploadPhoto), ctx, userID, content, contentType)
}

// UploadPhotos mocks base method.
func (m *MockProfileService) UploadPhotos(ctx context.Context, userID uuid.UUID, photos []*multipart.FileHeader) ([]domain.UserPhoto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPhotos", ctx, userID, photos)
	ret0, _ := ret[0].([]domain.UserPhoto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPhotos indicates an expected call of UploadPhotos.
func (mr *MockProfileServiceMockRecorder) UploadPhotos(ctx, userID, photos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPhotos", reflect.TypeOf((*MockProfileService)(nil).UploadPhotos), ctx, userID, photos)
}

// ValidatePreferencesUpdate mocks base method.
func (m *MockProfileService) ValidatePreferencesUpdate(ctx context.Context, updateData *domain.PreferencesUpdateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePreferencesUpdate", ctx, updateData)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePreferencesUpdate indicates an expected call of ValidatePreferencesUpdate.
func (mr *MockProfileServiceMockRecorder) ValidatePreferencesUpdate(ctx, updateData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePreferencesUpdate", reflect.TypeOf((*MockProfileService)(nil).ValidatePreferencesUpdate), ctx, updateData)
}

// ValidateProfileUpdate mocks base method.
func (m *MockProfileService) ValidateProfileUpdate(ctx context.Context, updateData *domain.ProfileUpdateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateProfileUpdate", ctx, updateData)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateProfileUpdate indicates an expected call of ValidateProfileUpdate.
func (mr *MockProfileServiceMockRecorder) ValidateProfileUpdate(ctx, updateData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateProfileUpdate", reflect.TypeOf((*MockProfileService)(nil).ValidateProfileUpdate), ctx, updateData)
}
