// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces/strike_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/interfaces/strike_repository.go -destination=tests/mocks/strike_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	constants "github.com/go-park-mail-ru/2025_2_RoadTo200/backend/internal/domain/constants"
	domain "github.com/go-park-mail-ru/2025_2_RoadTo200/backend/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockStrikeRepository is a mock of StrikeRepository interface.
type MockStrikeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStrikeRepositoryMockRecorder
	isgomock struct{}
}

// MockStrikeRepositoryMockRecorder is the mock recorder for MockStrikeRepository.
type MockStrikeRepositoryMockRecorder struct {
	mock *MockStrikeRepository
}

// NewMockStrikeRepository creates a new mock instance.
func NewMockStrikeRepository(ctrl *gomock.Controller) *MockStrikeRepository {
	mock := &MockStrikeRepository{ctrl: ctrl}
	mock.recorder = &MockStrikeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrikeRepository) EXPECT() *MockStrikeRepositoryMockRecorder {
	return m.recorder
}

// CreateStrike mocks base method.
func (m *MockStrikeRepository) CreateStrike(ctx context.Context, strike *domain.Strike) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStrike", ctx, strike)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStrike indicates an expected call of CreateStrike.
func (mr *MockStrikeRepositoryMockRecorder) CreateStrike(ctx, strike any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStrike", reflect.TypeOf((*MockStrikeRepository)(nil).CreateStrike), ctx, strike)
}

// DeleteStrike mocks base method.
func (m *MockStrikeRepository) DeleteStrike(ctx context.Context, strikeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStrike", ctx, strikeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStrike indicates an expected call of DeleteStrike.
func (mr *MockStrikeRepositoryMockRecorder) DeleteStrike(ctx, strikeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStrike", reflect.TypeOf((*MockStrikeRepository)(nil).DeleteStrike), ctx, strikeID)
}

// GetStrikeByID mocks base method.
func (m *MockStrikeRepository) GetStrikeByID(ctx context.Context, strikeID string) (*domain.Strike, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStrikeByID", ctx, strikeID)
	ret0, _ := ret[0].(*domain.Strike)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStrikeByID indicates an expected call of GetStrikeByID.
func (mr *MockStrikeRepositoryMockRecorder) GetStrikeByID(ctx, strikeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStrikeByID", reflect.TypeOf((*MockStrikeRepository)(nil).GetStrikeByID), ctx, strikeID)
}

// GetStrikesByDateRange mocks base method.
func (m *MockStrikeRepository) GetStrikesByDateRange(ctx context.Context, from, to time.Time, limit, offset int) ([]*domain.Strike, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStrikesByDateRange", ctx, from, to, limit, offset)
	ret0, _ := ret[0].([]*domain.Strike)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStrikesByDateRange indicates an expected call of GetStrikesByDateRange.
func (mr *MockStrikeRepositoryMockRecorder) GetStrikesByDateRange(ctx, from, to, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStrikesByDateRange", reflect.TypeOf((*MockStrikeRepository)(nil).GetStrikesByDateRange), ctx, from, to, limit, offset)
}

// GetStrikesByType mocks base method.
func (m *MockStrikeRepository) GetStrikesByType(ctx context.Context, strikeType constants.StrikeType, limit, offset int) ([]*domain.Strike, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStrikesByType", ctx, strikeType, limit, offset)
	ret0, _ := ret[0].([]*domain.Strike)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStrikesByType indicates an expected call of GetStrikesByType.
func (mr *MockStrikeRepositoryMockRecorder) GetStrikesByType(ctx, strikeType, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStrikesByType", reflect.TypeOf((*MockStrikeRepository)(nil).GetStrikesByType), ctx, strikeType, limit, offset)
}

// GetStrikesByUserID mocks base method.
func (m *MockStrikeRepository) GetStrikesByUserID(ctx context.Context, userID string, limit, offset int) ([]*domain.Strike, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStrikesByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*domain.Strike)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStrikesByUserID indicates an expected call of GetStrikesByUserID.
func (mr *MockStrikeRepositoryMockRecorder) GetStrikesByUserID(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStrikesByUserID", reflect.TypeOf((*MockStrikeRepository)(nil).GetStrikesByUserID), ctx, userID, limit, offset)
}

// HasActiveStrikeFromUser mocks base method.
func (m *MockStrikeRepository) HasActiveStrikeFromUser(ctx context.Context, reporterID, targetUserID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveStrikeFromUser", ctx, reporterID, targetUserID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasActiveStrikeFromUser indicates an expected call of HasActiveStrikeFromUser.
func (mr *MockStrikeRepositoryMockRecorder) HasActiveStrikeFromUser(ctx, reporterID, targetUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveStrikeFromUser", reflect.TypeOf((*MockStrikeRepository)(nil).HasActiveStrikeFromUser), ctx, reporterID, targetUserID)
}

// UpdateStrikeStatus mocks base method.
func (m *MockStrikeRepository) UpdateStrikeStatus(ctx context.Context, strikeID string, status constants.StrikeStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStrikeStatus", ctx, strikeID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStrikeStatus indicates an expected call of UpdateStrikeStatus.
func (mr *MockStrikeRepositoryMockRecorder) UpdateStrikeStatus(ctx, strikeID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStrikeStatus", reflect.TypeOf((*MockStrikeRepository)(nil).UpdateStrikeStatus), ctx, strikeID, status)
}
