// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces/swipe_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2025_2_RoadTo200/backend/internal/domain/entities"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockSwipeRepository is a mock of SwipeRepository interface.
type MockSwipeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSwipeRepositoryMockRecorder
}

// MockSwipeRepositoryMockRecorder is the mock recorder for MockSwipeRepository.
type MockSwipeRepositoryMockRecorder struct {
	mock *MockSwipeRepository
}

// NewMockSwipeRepository creates a new mock instance.
func NewMockSwipeRepository(ctrl *gomock.Controller) *MockSwipeRepository {
	mock := &MockSwipeRepository{ctrl: ctrl}
	mock.recorder = &MockSwipeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSwipeRepository) EXPECT() *MockSwipeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSwipeRepository) Create(ctx context.Context, swipe *domain.Swipe) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, swipe)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSwipeRepositoryMockRecorder) Create(ctx, swipe interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSwipeRepository)(nil).Create), ctx, swipe)
}

// Exists mocks base method.
func (m *MockSwipeRepository) Exists(ctx context.Context, swiperID, targetID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, swiperID, targetID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockSwipeRepositoryMockRecorder) Exists(ctx, swiperID, targetID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockSwipeRepository)(nil).Exists), ctx, swiperID, targetID)
}

// GetBySwiperAndTarget mocks base method.
func (m *MockSwipeRepository) GetBySwiperAndTarget(ctx context.Context, swiperID, targetID uuid.UUID) (*domain.Swipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySwiperAndTarget", ctx, swiperID, targetID)
	ret0, _ := ret[0].(*domain.Swipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySwiperAndTarget indicates an expected call of GetBySwiperAndTarget.
func (mr *MockSwipeRepositoryMockRecorder) GetBySwiperAndTarget(ctx, swiperID, targetID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySwiperAndTarget", reflect.TypeOf((*MockSwipeRepository)(nil).GetBySwiperAndTarget), ctx, swiperID, targetID)
}

// GetMutualLikes mocks base method.
func (m *MockSwipeRepository) GetMutualLikes(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMutualLikes", ctx, userID)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMutualLikes indicates an expected call of GetMutualLikes.
func (mr *MockSwipeRepositoryMockRecorder) GetMutualLikes(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMutualLikes", reflect.TypeOf((*MockSwipeRepository)(nil).GetMutualLikes), ctx, userID)
}

// GetSwipesBySwiper mocks base method.
func (m *MockSwipeRepository) GetSwipesBySwiper(ctx context.Context, swiperID uuid.UUID, limit, offset int) ([]domain.Swipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSwipesBySwiper", ctx, swiperID, limit, offset)
	ret0, _ := ret[0].([]domain.Swipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSwipesBySwiper indicates an expected call of GetSwipesBySwiper.
func (mr *MockSwipeRepositoryMockRecorder) GetSwipesBySwiper(ctx, swiperID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSwipesBySwiper", reflect.TypeOf((*MockSwipeRepository)(nil).GetSwipesBySwiper), ctx, swiperID, limit, offset)
}

// GetSwipesByTarget mocks base method.
func (m *MockSwipeRepository) GetSwipesByTarget(ctx context.Context, targetID uuid.UUID, limit, offset int) ([]domain.Swipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSwipesByTarget", ctx, targetID, limit, offset)
	ret0, _ := ret[0].([]domain.Swipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSwipesByTarget indicates an expected call of GetSwipesByTarget.
func (mr *MockSwipeRepositoryMockRecorder) GetSwipesByTarget(ctx, targetID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSwipesByTarget", reflect.TypeOf((*MockSwipeRepository)(nil).GetSwipesByTarget), ctx, targetID, limit, offset)
}

// GetSwipesStats mocks base method.
func (m *MockSwipeRepository) GetSwipesStats(ctx context.Context, userID uuid.UUID) (int, int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSwipesStats", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetSwipesStats indicates an expected call of GetSwipesStats.
func (mr *MockSwipeRepositoryMockRecorder) GetSwipesStats(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSwipesStats", reflect.TypeOf((*MockSwipeRepository)(nil).GetSwipesStats), ctx, userID)
}
