// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces/user_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2025_2_RoadTo200/backend/internal/domain/entities"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
}

// Delete mocks base method.
func (m *MockUserRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepository)(nil).Delete), ctx, id)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// GetByPhone mocks base method.
func (m *MockUserRepository) GetByPhone(ctx context.Context, phone string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPhone", ctx, phone)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPhone indicates an expected call of GetByPhone.
func (mr *MockUserRepositoryMockRecorder) GetByPhone(ctx, phone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPhone", reflect.TypeOf((*MockUserRepository)(nil).GetByPhone), ctx, phone)
}

// GetUsersByIDs mocks base method.
func (m *MockUserRepository) GetUsersByIDs(ctx context.Context, ids []uuid.UUID) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByIDs", ctx, ids)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByIDs indicates an expected call of GetUsersByIDs.
func (mr *MockUserRepositoryMockRecorder) GetUsersByIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByIDs", reflect.TypeOf((*MockUserRepository)(nil).GetUsersByIDs), ctx, ids)
}

// GetUsersForFeed mocks base method.
func (m *MockUserRepository) GetUsersForFeed(ctx context.Context, userID uuid.UUID, limit, offset int) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersForFeed", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersForFeed indicates an expected call of GetUsersForFeed.
func (mr *MockUserRepositoryMockRecorder) GetUsersForFeed(ctx, userID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersForFeed", reflect.TypeOf((*MockUserRepository)(nil).GetUsersForFeed), ctx, userID, limit, offset)
}

// Update mocks base method.
func (m *MockUserRepository) Update(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), ctx, user)
}

// UpdateLastActive mocks base method.
func (m *MockUserRepository) UpdateLastActive(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastActive", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastActive indicates an expected call of UpdateLastActive.
func (mr *MockUserRepositoryMockRecorder) UpdateLastActive(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastActive", reflect.TypeOf((*MockUserRepository)(nil).UpdateLastActive), ctx, userID)
}

// MockUserPhotoRepository is a mock of UserPhotoRepository interface.
type MockUserPhotoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserPhotoRepositoryMockRecorder
}

// MockUserPhotoRepositoryMockRecorder is the mock recorder for MockUserPhotoRepository.
type MockUserPhotoRepositoryMockRecorder struct {
	mock *MockUserPhotoRepository
}

// NewMockUserPhotoRepository creates a new mock instance.
func NewMockUserPhotoRepository(ctrl *gomock.Controller) *MockUserPhotoRepository {
	mock := &MockUserPhotoRepository{ctrl: ctrl}
	mock.recorder = &MockUserPhotoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserPhotoRepository) EXPECT() *MockUserPhotoRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserPhotoRepository) Create(ctx context.Context, photo *domain.UserPhoto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, photo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserPhotoRepositoryMockRecorder) Create(ctx, photo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserPhotoRepository)(nil).Create), ctx, photo)
}

// Delete mocks base method.
func (m *MockUserPhotoRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserPhotoRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserPhotoRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockUserPhotoRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.UserPhoto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.UserPhoto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserPhotoRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserPhotoRepository)(nil).GetByID), ctx, id)
}

// GetByUserID mocks base method.
func (m *MockUserPhotoRepository) GetByUserID(ctx context.Context, userID uuid.UUID) ([]domain.UserPhoto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]domain.UserPhoto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockUserPhotoRepositoryMockRecorder) GetByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockUserPhotoRepository)(nil).GetByUserID), ctx, userID)
}

// Update mocks base method.
func (m *MockUserPhotoRepository) Update(ctx context.Context, photo *domain.UserPhoto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, photo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserPhotoRepositoryMockRecorder) Update(ctx, photo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserPhotoRepository)(nil).Update), ctx, photo)
}

// UpdateDisplayOrder mocks base method.
func (m *MockUserPhotoRepository) UpdateDisplayOrder(ctx context.Context, userID uuid.UUID, photos []domain.UserPhoto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDisplayOrder", ctx, userID, photos)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDisplayOrder indicates an expected call of UpdateDisplayOrder.
func (mr *MockUserPhotoRepositoryMockRecorder) UpdateDisplayOrder(ctx, userID, photos interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDisplayOrder", reflect.TypeOf((*MockUserPhotoRepository)(nil).UpdateDisplayOrder), ctx, userID, photos)
}

// MockUserPreferenceRepository is a mock of UserPreferenceRepository interface.
type MockUserPreferenceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserPreferenceRepositoryMockRecorder
}

// MockUserPreferenceRepositoryMockRecorder is the mock recorder for MockUserPreferenceRepository.
type MockUserPreferenceRepositoryMockRecorder struct {
	mock *MockUserPreferenceRepository
}

// NewMockUserPreferenceRepository creates a new mock instance.
func NewMockUserPreferenceRepository(ctrl *gomock.Controller) *MockUserPreferenceRepository {
	mock := &MockUserPreferenceRepository{ctrl: ctrl}
	mock.recorder = &MockUserPreferenceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserPreferenceRepository) EXPECT() *MockUserPreferenceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserPreferenceRepository) Create(ctx context.Context, preference *domain.UserPreference) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, preference)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserPreferenceRepositoryMockRecorder) Create(ctx, preference interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserPreferenceRepository)(nil).Create), ctx, preference)
}

// Delete mocks base method.
func (m *MockUserPreferenceRepository) Delete(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserPreferenceRepositoryMockRecorder) Delete(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserPreferenceRepository)(nil).Delete), ctx, userID)
}

// GetByUserID mocks base method.
func (m *MockUserPreferenceRepository) GetByUserID(ctx context.Context, userID uuid.UUID) (*domain.UserPreference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.UserPreference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockUserPreferenceRepositoryMockRecorder) GetByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockUserPreferenceRepository)(nil).GetByUserID), ctx, userID)
}

// GetInterests mocks base method.
func (m *MockUserPreferenceRepository) GetInterests(ctx context.Context, userID uuid.UUID) ([]domain.Interest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInterests", ctx, userID)
	ret0, _ := ret[0].([]domain.Interest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInterests indicates an expected call of GetInterests.
func (mr *MockUserPreferenceRepositoryMockRecorder) GetInterests(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInterests", reflect.TypeOf((*MockUserPreferenceRepository)(nil).GetInterests), ctx, userID)
}

// Update mocks base method.
func (m *MockUserPreferenceRepository) Update(ctx context.Context, preference *domain.UserPreference) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, preference)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserPreferenceRepositoryMockRecorder) Update(ctx, preference interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserPreferenceRepository)(nil).Update), ctx, preference)
}

// UpdateInterests mocks base method.
func (m *MockUserPreferenceRepository) UpdateInterests(ctx context.Context, userID uuid.UUID, interest []domain.Interest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInterests", ctx, userID, interest)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInterests indicates an expected call of UpdateInterests.
func (mr *MockUserPreferenceRepositoryMockRecorder) UpdateInterests(ctx, userID, interest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInterests", reflect.TypeOf((*MockUserPreferenceRepository)(nil).UpdateInterests), ctx, userID, interest)
}
