services:
  postgres:
    image: postgres:17
    container_name: postgres_vk
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PSWD}
      POSTGRES_DB: ${PG_BASE}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_vk_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_vk
    ports:
      - "${RD_PORT}:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${RD_PSWD}
    volumes:
      - redis_vk_data:/data

  minio:
    image: minio/minio:latest
    container_name: minio_vk
    ports:
      - "${MN_PORT}:9000"   # API порт
      - "${MN_ADMN}:9001"   # Web UI порт
    environment:
      MINIO_ROOT_USER: ${MN_USER}
      MINIO_ROOT_PASSWORD: ${MN_PSWD}
    volumes:
      - minio_vk_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MN_PORT}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc:latest
    container_name: minio_vk_createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:${MN_PORT} minioadmin minioadmin;
      /usr/bin/mc mb myminio/terabithia-photos;
      /usr/bin/mc anonymous set public myminio/terabithia-photos;
      echo 'Buckets created successfully';
      exit 0;
      "

  adminer:
    image: adminer:latest
    container_name: adminer_vk
    restart: always
    ports:
      - "${AD_PORT}:8080"

  node-exporter:
    image: prom/node-exporter:v1.10.2
    container_name: node_exporter_vk
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - monitoring

  # Prometheus
  prometheus:
    image: prom/prometheus:v3.7.3
    container_name: prometheus_vk
    ports:
      - "${PT_PORT}:9090"
    volumes:
      - ./infra/monitoring/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_vk_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    depends_on:
      - node-exporter
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Grafana
  grafana:
    image: grafana/grafana:12.3
    container_name: grafana_vk
    ports:
      - "${GF_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./infra/grafana:/etc/grafana/provisioning
      - grafana_vk_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

volumes:
  postgres_vk_data:
  redis_vk_data:
  minio_vk_data:
  prometheus_vk_data:
  grafana_vk_data:

networks:
  monitoring:
    driver: bridge
