// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	constants "github.com/go-park-mail-ru/2025_2_RoadTo200/backend/internal/domain/constants"
	entities "github.com/go-park-mail-ru/2025_2_RoadTo200/backend/internal/domain/entities"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonA9727c4fDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(in *jlexer.Lexer, out *UnmatchRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "target_user_id":
			out.TargetUserID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA9727c4fEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(out *jwriter.Writer, in UnmatchRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"target_user_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.TargetUserID))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UnmatchRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA9727c4fEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UnmatchRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA9727c4fDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(l, v)
}
func easyjsonA9727c4fDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(in *jlexer.Lexer, out *MatchesResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "matches":
			if in.IsNull() {
				in.Skip()
				out.Matches = nil
			} else {
				in.Delim('[')
				if out.Matches == nil {
					if !in.IsDelim(']') {
						out.Matches = make([]MatchResponse, 0, 0)
					} else {
						out.Matches = []MatchResponse{}
					}
				} else {
					out.Matches = (out.Matches)[:0]
				}
				for !in.IsDelim(']') {
					var v1 MatchResponse
					(v1).UnmarshalEasyJSON(in)
					out.Matches = append(out.Matches, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "total":
			out.Total = int(in.Int())
		case "limit":
			out.Limit = int(in.Int())
		case "offset":
			out.Offset = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA9727c4fEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(out *jwriter.Writer, in MatchesResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"matches\":"
		out.RawString(prefix[1:])
		if in.Matches == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Matches {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix)
		out.Int(int(in.Total))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int(int(in.Limit))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int(int(in.Offset))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MatchesResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA9727c4fEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MatchesResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA9727c4fDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(l, v)
}
func easyjsonA9727c4fDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto2(in *jlexer.Lexer, out *MatchResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "match":
			easyjsonA9727c4fDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(in, &out.Match)
		case "user":
			easyjsonA9727c4fDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities1(in, &out.User)
		case "photos":
			if in.IsNull() {
				in.Skip()
				out.Photos = nil
			} else {
				in.Delim('[')
				if out.Photos == nil {
					if !in.IsDelim(']') {
						out.Photos = make([]string, 0, 4)
					} else {
						out.Photos = []string{}
					}
				} else {
					out.Photos = (out.Photos)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					v4 = string(in.String())
					out.Photos = append(out.Photos, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "age":
			out.Age = int(in.Int())
		case "description":
			out.Description = string(in.String())
		case "photos_count":
			out.PhotosCount = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA9727c4fEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto2(out *jwriter.Writer, in MatchResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"match\":"
		out.RawString(prefix[1:])
		easyjsonA9727c4fEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(out, in.Match)
	}
	{
		const prefix string = ",\"user\":"
		out.RawString(prefix)
		easyjsonA9727c4fEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities1(out, in.User)
	}
	{
		const prefix string = ",\"photos\":"
		out.RawString(prefix)
		if in.Photos == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Photos {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"age\":"
		out.RawString(prefix)
		out.Int(int(in.Age))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"photos_count\":"
		out.RawString(prefix)
		out.Int(int(in.PhotosCount))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MatchResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonA9727c4fEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto2(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MatchResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonA9727c4fDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto2(l, v)
}
func easyjsonA9727c4fDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities1(in *jlexer.Lexer, out *entities.User) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		case "email":
			out.Email = string(in.String())
		case "phone":
			if in.IsNull() {
				in.Skip()
				out.Phone = nil
			} else {
				if out.Phone == nil {
					out.Phone = new(string)
				}
				*out.Phone = string(in.String())
			}
		case "name":
			out.Name = string(in.String())
		case "birth_date":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.BirthDate).UnmarshalJSON(data))
			}
		case "gender":
			out.Gender = constants.Gender(in.String())
		case "bio":
			if in.IsNull() {
				in.Skip()
				out.Bio = nil
			} else {
				if out.Bio == nil {
					out.Bio = new(string)
				}
				*out.Bio = string(in.String())
			}
		case "city":
			if in.IsNull() {
				in.Skip()
				out.City = nil
			} else {
				if out.City == nil {
					out.City = new(string)
				}
				*out.City = string(in.String())
			}
		case "artist":
			if in.IsNull() {
				in.Skip()
				out.Artist = nil
			} else {
				if out.Artist == nil {
					out.Artist = new(string)
				}
				*out.Artist = string(in.String())
			}
		case "quote":
			if in.IsNull() {
				in.Skip()
				out.Quote = nil
			} else {
				if out.Quote == nil {
					out.Quote = new(string)
				}
				*out.Quote = string(in.String())
			}
		case "is_verified":
			out.IsVerified = bool(in.Bool())
		case "is_premium":
			out.IsPremium = bool(in.Bool())
		case "super_likes_count":
			out.SuperLikesCount = int(in.Int())
		case "last_active":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.LastActive).UnmarshalJSON(data))
			}
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA9727c4fEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities1(out *jwriter.Writer, in entities.User) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	if in.Phone != nil {
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		out.String(string(*in.Phone))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"birth_date\":"
		out.RawString(prefix)
		out.Raw((in.BirthDate).MarshalJSON())
	}
	{
		const prefix string = ",\"gender\":"
		out.RawString(prefix)
		out.String(string(in.Gender))
	}
	if in.Bio != nil {
		const prefix string = ",\"bio\":"
		out.RawString(prefix)
		out.String(string(*in.Bio))
	}
	if in.City != nil {
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(*in.City))
	}
	if in.Artist != nil {
		const prefix string = ",\"artist\":"
		out.RawString(prefix)
		out.String(string(*in.Artist))
	}
	if in.Quote != nil {
		const prefix string = ",\"quote\":"
		out.RawString(prefix)
		out.String(string(*in.Quote))
	}
	{
		const prefix string = ",\"is_verified\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsVerified))
	}
	{
		const prefix string = ",\"is_premium\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsPremium))
	}
	{
		const prefix string = ",\"super_likes_count\":"
		out.RawString(prefix)
		out.Int(int(in.SuperLikesCount))
	}
	{
		const prefix string = ",\"last_active\":"
		out.RawString(prefix)
		out.Raw((in.LastActive).MarshalJSON())
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}
func easyjsonA9727c4fDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(in *jlexer.Lexer, out *entities.Match) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		case "user1_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.User1ID).UnmarshalText(data))
			}
		case "user2_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.User2ID).UnmarshalText(data))
			}
		case "is_active":
			out.IsActive = bool(in.Bool())
		case "matched_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.MatchedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonA9727c4fEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(out *jwriter.Writer, in entities.Match) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"user1_id\":"
		out.RawString(prefix)
		out.RawText((in.User1ID).MarshalText())
	}
	{
		const prefix string = ",\"user2_id\":"
		out.RawString(prefix)
		out.RawText((in.User2ID).MarshalText())
	}
	{
		const prefix string = ",\"is_active\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsActive))
	}
	{
		const prefix string = ",\"matched_at\":"
		out.RawString(prefix)
		out.Raw((in.MatchedAt).MarshalJSON())
	}
	out.RawByte('}')
}
