// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	constants "github.com/go-park-mail-ru/2025_2_RoadTo200/backend/internal/domain/constants"
	entities "github.com/go-park-mail-ru/2025_2_RoadTo200/backend/internal/domain/entities"
	uuid "github.com/google/uuid"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5b7208a7DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(in *jlexer.Lexer, out *NotificationsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "notifications":
			if in.IsNull() {
				in.Skip()
				out.Notifications = nil
			} else {
				in.Delim('[')
				if out.Notifications == nil {
					if !in.IsDelim(']') {
						out.Notifications = make([]entities.Notification, 0, 0)
					} else {
						out.Notifications = []entities.Notification{}
					}
				} else {
					out.Notifications = (out.Notifications)[:0]
				}
				for !in.IsDelim(']') {
					var v1 entities.Notification
					easyjson5b7208a7DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(in, &v1)
					out.Notifications = append(out.Notifications, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "total":
			out.Total = int(in.Int())
		case "limit":
			out.Limit = int(in.Int())
		case "offset":
			out.Offset = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5b7208a7EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(out *jwriter.Writer, in NotificationsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"notifications\":"
		out.RawString(prefix[1:])
		if in.Notifications == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Notifications {
				if v2 > 0 {
					out.RawByte(',')
				}
				easyjson5b7208a7EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(out, v3)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix)
		out.Int(int(in.Total))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int(int(in.Limit))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int(int(in.Offset))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NotificationsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5b7208a7EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NotificationsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5b7208a7DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(l, v)
}
func easyjson5b7208a7DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(in *jlexer.Lexer, out *entities.Notification) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		case "user_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.UserID).UnmarshalText(data))
			}
		case "type":
			out.Type = constants.NotificationType(in.String())
		case "from_user_id":
			if in.IsNull() {
				in.Skip()
				out.FromUserID = nil
			} else {
				if out.FromUserID == nil {
					out.FromUserID = new(uuid.UUID)
				}
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((*out.FromUserID).UnmarshalText(data))
				}
			}
		case "match_id":
			if in.IsNull() {
				in.Skip()
				out.MatchID = nil
			} else {
				if out.MatchID == nil {
					out.MatchID = new(uuid.UUID)
				}
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((*out.MatchID).UnmarshalText(data))
				}
			}
		case "is_read":
			out.IsRead = bool(in.Bool())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5b7208a7EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(out *jwriter.Writer, in entities.Notification) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.RawText((in.UserID).MarshalText())
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	if in.FromUserID != nil {
		const prefix string = ",\"from_user_id\":"
		out.RawString(prefix)
		out.RawText((*in.FromUserID).MarshalText())
	}
	if in.MatchID != nil {
		const prefix string = ",\"match_id\":"
		out.RawString(prefix)
		out.RawText((*in.MatchID).MarshalText())
	}
	{
		const prefix string = ",\"is_read\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsRead))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}
