// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC1fe9762DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(in *jlexer.Lexer, out *CreatePaymentResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "payment_url":
			out.PaymentURL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC1fe9762EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(out *jwriter.Writer, in CreatePaymentResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"payment_url\":"
		out.RawString(prefix[1:])
		out.String(string(in.PaymentURL))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreatePaymentResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC1fe9762EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreatePaymentResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC1fe9762DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(l, v)
}
func easyjsonC1fe9762DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(in *jlexer.Lexer, out *CreatePaymentRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount":
			out.Amount = float64(in.Float64())
		case "planId":
			out.PlanID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC1fe9762EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(out *jwriter.Writer, in CreatePaymentRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.Amount))
	}
	{
		const prefix string = ",\"planId\":"
		out.RawString(prefix)
		out.String(string(in.PlanID))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreatePaymentRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC1fe9762EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreatePaymentRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC1fe9762DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(l, v)
}
