// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	constants "github.com/go-park-mail-ru/2025_2_RoadTo200/backend/internal/domain/constants"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC9d05897DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(in *jlexer.Lexer, out *UpdateProfileRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "phone":
			if in.IsNull() {
				in.Skip()
				out.Phone = nil
			} else {
				if out.Phone == nil {
					out.Phone = new(string)
				}
				*out.Phone = string(in.String())
			}
		case "birth_date":
			if in.IsNull() {
				in.Skip()
				out.BirthDate = nil
			} else {
				if out.BirthDate == nil {
					out.BirthDate = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.BirthDate).UnmarshalJSON(data))
				}
			}
		case "gender":
			out.Gender = constants.Gender(in.String())
		case "bio":
			if in.IsNull() {
				in.Skip()
				out.Bio = nil
			} else {
				if out.Bio == nil {
					out.Bio = new(string)
				}
				*out.Bio = string(in.String())
			}
		case "artist":
			if in.IsNull() {
				in.Skip()
				out.Artist = nil
			} else {
				if out.Artist == nil {
					out.Artist = new(string)
				}
				*out.Artist = string(in.String())
			}
		case "quote":
			if in.IsNull() {
				in.Skip()
				out.Quote = nil
			} else {
				if out.Quote == nil {
					out.Quote = new(string)
				}
				*out.Quote = string(in.String())
			}
		case "latitude":
			if in.IsNull() {
				in.Skip()
				out.Latitude = nil
			} else {
				if out.Latitude == nil {
					out.Latitude = new(float64)
				}
				*out.Latitude = float64(in.Float64())
			}
		case "longitude":
			if in.IsNull() {
				in.Skip()
				out.Longitude = nil
			} else {
				if out.Longitude == nil {
					out.Longitude = new(float64)
				}
				*out.Longitude = float64(in.Float64())
			}
		case "show_gender":
			out.ShowGender = constants.GenderPreference(in.String())
		case "age_min":
			out.AgeMin = int(in.Int())
		case "age_max":
			out.AgeMax = int(in.Int())
		case "max_distance":
			out.MaxDistance = int(in.Int())
		case "global_search":
			out.GlobalSearch = bool(in.Bool())
		case "photo_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.PhotoID).UnmarshalText(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC9d05897EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(out *jwriter.Writer, in UpdateProfileRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Name != "" {
		const prefix string = ",\"name\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	if in.Phone != nil {
		const prefix string = ",\"phone\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Phone))
	}
	if in.BirthDate != nil {
		const prefix string = ",\"birth_date\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((*in.BirthDate).MarshalJSON())
	}
	if in.Gender != "" {
		const prefix string = ",\"gender\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Gender))
	}
	if in.Bio != nil {
		const prefix string = ",\"bio\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Bio))
	}
	if in.Artist != nil {
		const prefix string = ",\"artist\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Artist))
	}
	if in.Quote != nil {
		const prefix string = ",\"quote\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Quote))
	}
	if in.Latitude != nil {
		const prefix string = ",\"latitude\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(*in.Latitude))
	}
	if in.Longitude != nil {
		const prefix string = ",\"longitude\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Float64(float64(*in.Longitude))
	}
	if in.ShowGender != "" {
		const prefix string = ",\"show_gender\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ShowGender))
	}
	if in.AgeMin != 0 {
		const prefix string = ",\"age_min\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.AgeMin))
	}
	if in.AgeMax != 0 {
		const prefix string = ",\"age_max\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.AgeMax))
	}
	if in.MaxDistance != 0 {
		const prefix string = ",\"max_distance\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.MaxDistance))
	}
	if in.GlobalSearch {
		const prefix string = ",\"global_search\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.GlobalSearch))
	}
	if true {
		const prefix string = ",\"photo_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.RawText((in.PhotoID).MarshalText())
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateProfileRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC9d05897EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateProfileRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC9d05897DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(l, v)
}
func easyjsonC9d05897DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(in *jlexer.Lexer, out *ProfileResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user":
			if m, ok := out.User.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.User.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.User = in.Interface()
			}
		case "preferences":
			if m, ok := out.Preferences.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Preferences.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Preferences = in.Interface()
			}
		case "photos":
			if m, ok := out.Photos.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Photos.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Photos = in.Interface()
			}
		case "interests":
			if m, ok := out.Interests.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Interests.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Interests = in.Interface()
			}
		case "is_liked":
			if in.IsNull() {
				in.Skip()
				out.IsLiked = nil
			} else {
				if out.IsLiked == nil {
					out.IsLiked = new(bool)
				}
				*out.IsLiked = bool(in.Bool())
			}
		case "is_matched":
			if in.IsNull() {
				in.Skip()
				out.IsMatched = nil
			} else {
				if out.IsMatched == nil {
					out.IsMatched = new(bool)
				}
				*out.IsMatched = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC9d05897EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(out *jwriter.Writer, in ProfileResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user\":"
		out.RawString(prefix[1:])
		if m, ok := in.User.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.User.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.User))
		}
	}
	if in.Preferences != nil {
		const prefix string = ",\"preferences\":"
		out.RawString(prefix)
		if m, ok := in.Preferences.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Preferences.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Preferences))
		}
	}
	if in.Photos != nil {
		const prefix string = ",\"photos\":"
		out.RawString(prefix)
		if m, ok := in.Photos.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Photos.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Photos))
		}
	}
	if in.Interests != nil {
		const prefix string = ",\"interests\":"
		out.RawString(prefix)
		if m, ok := in.Interests.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Interests.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Interests))
		}
	}
	if in.IsLiked != nil {
		const prefix string = ",\"is_liked\":"
		out.RawString(prefix)
		out.Bool(bool(*in.IsLiked))
	}
	if in.IsMatched != nil {
		const prefix string = ",\"is_matched\":"
		out.RawString(prefix)
		out.Bool(bool(*in.IsMatched))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ProfileResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC9d05897EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ProfileResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC9d05897DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(l, v)
}
