// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson62a7fa70DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(in *jlexer.Lexer, out *SessionUserResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "email":
			out.Email = string(in.String())
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson62a7fa70EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(out *jwriter.Writer, in SessionUserResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SessionUserResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson62a7fa70EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SessionUserResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson62a7fa70DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(l, v)
}
func easyjson62a7fa70DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(in *jlexer.Lexer, out *SessionResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "authenticated":
			out.Authenticated = bool(in.Bool())
		case "user":
			if in.IsNull() {
				in.Skip()
				out.User = nil
			} else {
				if out.User == nil {
					out.User = new(SessionUserResponse)
				}
				(*out.User).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson62a7fa70EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(out *jwriter.Writer, in SessionResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"authenticated\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Authenticated))
	}
	if in.User != nil {
		const prefix string = ",\"user\":"
		out.RawString(prefix)
		(*in.User).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SessionResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson62a7fa70EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SessionResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson62a7fa70DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(l, v)
}
