// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	constants "github.com/go-park-mail-ru/2025_2_RoadTo200/backend/internal/domain/constants"
	uuid "github.com/google/uuid"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonCab61becDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(in *jlexer.Lexer, out *StrikesListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "strikes":
			if in.IsNull() {
				in.Skip()
				out.Strikes = nil
			} else {
				in.Delim('[')
				if out.Strikes == nil {
					if !in.IsDelim(']') {
						out.Strikes = make([]StrikeResponse, 0, 0)
					} else {
						out.Strikes = []StrikeResponse{}
					}
				} else {
					out.Strikes = (out.Strikes)[:0]
				}
				for !in.IsDelim(']') {
					var v1 StrikeResponse
					(v1).UnmarshalEasyJSON(in)
					out.Strikes = append(out.Strikes, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "total":
			out.Total = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCab61becEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(out *jwriter.Writer, in StrikesListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"strikes\":"
		out.RawString(prefix[1:])
		if in.Strikes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Strikes {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix)
		out.Int(int(in.Total))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StrikesListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCab61becEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StrikesListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCab61becDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(l, v)
}
func easyjsonCab61becDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(in *jlexer.Lexer, out *StrikeTypeStat) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "pending":
			out.Pending = int(in.Int())
		case "approved":
			out.Approved = int(in.Int())
		case "rejected":
			out.Rejected = int(in.Int())
		case "resolved":
			out.Resolved = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCab61becEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(out *jwriter.Writer, in StrikeTypeStat) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"pending\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Pending))
	}
	{
		const prefix string = ",\"approved\":"
		out.RawString(prefix)
		out.Int(int(in.Approved))
	}
	{
		const prefix string = ",\"rejected\":"
		out.RawString(prefix)
		out.Int(int(in.Rejected))
	}
	{
		const prefix string = ",\"resolved\":"
		out.RawString(prefix)
		out.Int(int(in.Resolved))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StrikeTypeStat) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCab61becEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StrikeTypeStat) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCab61becDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(l, v)
}
func easyjsonCab61becDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto2(in *jlexer.Lexer, out *StrikeStatusUpdateRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = constants.StrikeStatus(in.String())
		case "moderator_id":
			if in.IsNull() {
				in.Skip()
				out.ModeratorID = nil
			} else {
				if out.ModeratorID == nil {
					out.ModeratorID = new(uuid.UUID)
				}
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((*out.ModeratorID).UnmarshalText(data))
				}
			}
		case "note":
			if in.IsNull() {
				in.Skip()
				out.Note = nil
			} else {
				if out.Note == nil {
					out.Note = new(string)
				}
				*out.Note = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCab61becEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto2(out *jwriter.Writer, in StrikeStatusUpdateRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	if in.ModeratorID != nil {
		const prefix string = ",\"moderator_id\":"
		out.RawString(prefix)
		out.RawText((*in.ModeratorID).MarshalText())
	}
	if in.Note != nil {
		const prefix string = ",\"note\":"
		out.RawString(prefix)
		out.String(string(*in.Note))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StrikeStatusUpdateRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCab61becEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto2(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StrikeStatusUpdateRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCab61becDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto2(l, v)
}
func easyjsonCab61becDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto3(in *jlexer.Lexer, out *StrikeStats) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user_id":
			out.UserID = string(in.String())
		case "total_strikes":
			out.TotalStrikes = int(in.Int())
		case "last_strike_at":
			if in.IsNull() {
				in.Skip()
				out.LastStrikeAt = nil
			} else {
				if out.LastStrikeAt == nil {
					out.LastStrikeAt = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.LastStrikeAt).UnmarshalJSON(data))
				}
			}
		case "strike_types":
			(out.StrikeTypes).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCab61becEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto3(out *jwriter.Writer, in StrikeStats) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"total_strikes\":"
		out.RawString(prefix)
		out.Int(int(in.TotalStrikes))
	}
	{
		const prefix string = ",\"last_strike_at\":"
		out.RawString(prefix)
		if in.LastStrikeAt == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.LastStrikeAt).MarshalJSON())
		}
	}
	{
		const prefix string = ",\"strike_types\":"
		out.RawString(prefix)
		(in.StrikeTypes).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StrikeStats) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCab61becEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto3(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StrikeStats) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCab61becDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto3(l, v)
}
func easyjsonCab61becDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto4(in *jlexer.Lexer, out *StrikeResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		case "reporter_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ReporterID).UnmarshalText(data))
			}
		case "target_user_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.TargetUserID).UnmarshalText(data))
			}
		case "type":
			out.Type = constants.StrikeType(in.String())
		case "reason":
			out.Reason = string(in.String())
		case "status":
			out.Status = constants.StrikeStatus(in.String())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
				out.UpdatedAt = nil
			} else {
				if out.UpdatedAt == nil {
					out.UpdatedAt = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		case "moderator_id":
			if in.IsNull() {
				in.Skip()
				out.ModeratorID = nil
			} else {
				if out.ModeratorID == nil {
					out.ModeratorID = new(uuid.UUID)
				}
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((*out.ModeratorID).UnmarshalText(data))
				}
			}
		case "moderator_note":
			if in.IsNull() {
				in.Skip()
				out.ModeratorNote = nil
			} else {
				if out.ModeratorNote == nil {
					out.ModeratorNote = new(string)
				}
				*out.ModeratorNote = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCab61becEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto4(out *jwriter.Writer, in StrikeResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"reporter_id\":"
		out.RawString(prefix)
		out.RawText((in.ReporterID).MarshalText())
	}
	{
		const prefix string = ",\"target_user_id\":"
		out.RawString(prefix)
		out.RawText((in.TargetUserID).MarshalText())
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	if in.UpdatedAt != nil {
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((*in.UpdatedAt).MarshalJSON())
	}
	if in.ModeratorID != nil {
		const prefix string = ",\"moderator_id\":"
		out.RawString(prefix)
		out.RawText((*in.ModeratorID).MarshalText())
	}
	if in.ModeratorNote != nil {
		const prefix string = ",\"moderator_note\":"
		out.RawString(prefix)
		out.String(string(*in.ModeratorNote))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StrikeResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCab61becEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto4(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StrikeResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCab61becDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto4(l, v)
}
func easyjsonCab61becDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto5(in *jlexer.Lexer, out *StrikeCreateRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "reporter_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ReporterID).UnmarshalText(data))
			}
		case "target_user_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.TargetUserID).UnmarshalText(data))
			}
		case "type":
			out.Type = constants.StrikeType(in.String())
		case "reason":
			out.Reason = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCab61becEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto5(out *jwriter.Writer, in StrikeCreateRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"reporter_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ReporterID).MarshalText())
	}
	{
		const prefix string = ",\"target_user_id\":"
		out.RawString(prefix)
		out.RawText((in.TargetUserID).MarshalText())
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StrikeCreateRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCab61becEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto5(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StrikeCreateRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCab61becDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto5(l, v)
}
