// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6d1cbcb6DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(in *jlexer.Lexer, out *SwipeResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "is_match":
			out.IsMatch = bool(in.Bool())
		case "match_id":
			out.MatchID = string(in.String())
		case "message":
			out.Message = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6d1cbcb6EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(out *jwriter.Writer, in SwipeResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"is_match\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.IsMatch))
	}
	if in.MatchID != "" {
		const prefix string = ",\"match_id\":"
		out.RawString(prefix)
		out.String(string(in.MatchID))
	}
	if in.Message != "" {
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SwipeResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6d1cbcb6EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SwipeResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6d1cbcb6DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto(l, v)
}
func easyjson6d1cbcb6DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(in *jlexer.Lexer, out *SwipeRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "card_id":
			out.CardID = string(in.String())
		case "action":
			out.Action = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6d1cbcb6EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(out *jwriter.Writer, in SwipeRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"card_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.CardID))
	}
	{
		const prefix string = ",\"action\":"
		out.RawString(prefix)
		out.String(string(in.Action))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SwipeRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6d1cbcb6EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SwipeRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6d1cbcb6DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalHandlerDto1(l, v)
}
