// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEea530c9DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(in *jlexer.Lexer, out *Match) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		case "user1_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.User1ID).UnmarshalText(data))
			}
		case "user2_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.User2ID).UnmarshalText(data))
			}
		case "is_active":
			out.IsActive = bool(in.Bool())
		case "matched_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.MatchedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEea530c9EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(out *jwriter.Writer, in Match) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"user1_id\":"
		out.RawString(prefix)
		out.RawText((in.User1ID).MarshalText())
	}
	{
		const prefix string = ",\"user2_id\":"
		out.RawString(prefix)
		out.RawText((in.User2ID).MarshalText())
	}
	{
		const prefix string = ",\"is_active\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsActive))
	}
	{
		const prefix string = ",\"matched_at\":"
		out.RawString(prefix)
		out.Raw((in.MatchedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Match) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEea530c9EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Match) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEea530c9DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(l, v)
}
