// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4086215fDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(in *jlexer.Lexer, out *Message) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		case "match_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.MatchID).UnmarshalText(data))
			}
		case "sender_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.SenderID).UnmarshalText(data))
			}
		case "receiver_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ReceiverID).UnmarshalText(data))
			}
		case "content":
			out.Content = string(in.String())
		case "is_read":
			out.IsRead = bool(in.Bool())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4086215fEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(out *jwriter.Writer, in Message) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"match_id\":"
		out.RawString(prefix)
		out.RawText((in.MatchID).MarshalText())
	}
	{
		const prefix string = ",\"sender_id\":"
		out.RawString(prefix)
		out.RawText((in.SenderID).MarshalText())
	}
	{
		const prefix string = ",\"receiver_id\":"
		out.RawString(prefix)
		out.RawText((in.ReceiverID).MarshalText())
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	{
		const prefix string = ",\"is_read\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsRead))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Message) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4086215fEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Message) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4086215fDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(l, v)
}
func easyjson4086215fDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities1(in *jlexer.Lexer, out *Conversation) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "match_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.MatchID).UnmarshalText(data))
			}
		case "other_user_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.OtherUserID).UnmarshalText(data))
			}
		case "other_user_name":
			out.OtherUserName = string(in.String())
		case "other_user_photo":
			out.OtherUserPhoto = string(in.String())
		case "last_message":
			out.LastMessage = string(in.String())
		case "last_message_time":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.LastMessageTime).UnmarshalJSON(data))
			}
		case "unread_count":
			out.UnreadCount = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4086215fEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities1(out *jwriter.Writer, in Conversation) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"match_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.MatchID).MarshalText())
	}
	{
		const prefix string = ",\"other_user_id\":"
		out.RawString(prefix)
		out.RawText((in.OtherUserID).MarshalText())
	}
	{
		const prefix string = ",\"other_user_name\":"
		out.RawString(prefix)
		out.String(string(in.OtherUserName))
	}
	{
		const prefix string = ",\"other_user_photo\":"
		out.RawString(prefix)
		out.String(string(in.OtherUserPhoto))
	}
	{
		const prefix string = ",\"last_message\":"
		out.RawString(prefix)
		out.String(string(in.LastMessage))
	}
	{
		const prefix string = ",\"last_message_time\":"
		out.RawString(prefix)
		out.Raw((in.LastMessageTime).MarshalJSON())
	}
	{
		const prefix string = ",\"unread_count\":"
		out.RawString(prefix)
		out.Int(int(in.UnreadCount))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Conversation) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4086215fEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Conversation) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4086215fDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities1(l, v)
}
func easyjson4086215fDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities2(in *jlexer.Lexer, out *ChatMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "message_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.MessageID).UnmarshalText(data))
			}
		case "match_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.MatchID).UnmarshalText(data))
			}
		case "sender_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.SenderID).UnmarshalText(data))
			}
		case "content":
			out.Content = string(in.String())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "error":
			out.Error = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4086215fEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities2(out *jwriter.Writer, in ChatMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if true {
		const prefix string = ",\"message_id\":"
		out.RawString(prefix)
		out.RawText((in.MessageID).MarshalText())
	}
	{
		const prefix string = ",\"match_id\":"
		out.RawString(prefix)
		out.RawText((in.MatchID).MarshalText())
	}
	if true {
		const prefix string = ",\"sender_id\":"
		out.RawString(prefix)
		out.RawText((in.SenderID).MarshalText())
	}
	if in.Content != "" {
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	if true {
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	if in.Error != "" {
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		out.String(string(in.Error))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChatMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4086215fEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities2(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChatMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4086215fDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities2(l, v)
}
