// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"
	constants "github.com/go-park-mail-ru/2025_2_RoadTo200/backend/internal/domain/constants"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson82fcc681DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(in *jlexer.Lexer, out *UserPreference) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user_id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.UserID).UnmarshalText(data))
			}
		case "show_gender":
			out.ShowGender = constants.GenderPreference(in.String())
		case "age_min":
			out.AgeMin = int(in.Int())
		case "age_max":
			out.AgeMax = int(in.Int())
		case "max_distance":
			out.MaxDistance = int(in.Int())
		case "global_search":
			out.GlobalSearch = bool(in.Bool())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson82fcc681EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(out *jwriter.Writer, in UserPreference) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.UserID).MarshalText())
	}
	{
		const prefix string = ",\"show_gender\":"
		out.RawString(prefix)
		out.String(string(in.ShowGender))
	}
	{
		const prefix string = ",\"age_min\":"
		out.RawString(prefix)
		out.Int(int(in.AgeMin))
	}
	{
		const prefix string = ",\"age_max\":"
		out.RawString(prefix)
		out.Int(int(in.AgeMax))
	}
	{
		const prefix string = ",\"max_distance\":"
		out.RawString(prefix)
		out.Int(int(in.MaxDistance))
	}
	{
		const prefix string = ",\"global_search\":"
		out.RawString(prefix)
		out.Bool(bool(in.GlobalSearch))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v *UserPreference) MarshalEasyJSON(w *jwriter.Writer) {
	if v == nil {
		w.RawString("null")
		return
	}
	easyjson82fcc681EncodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(w, *v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserPreference) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson82fcc681DecodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(l, v)
}
