// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"
	constants "github.com/go-park-mail-ru/2025_2_RoadTo200/backend/internal/domain/constants"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9e1087fdDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(in *jlexer.Lexer, out *User) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		case "email":
			out.Email = string(in.String())
		case "phone":
			if in.IsNull() {
				in.Skip()
				out.Phone = nil
			} else {
				if out.Phone == nil {
					out.Phone = new(string)
				}
				*out.Phone = string(in.String())
			}
		case "name":
			out.Name = string(in.String())
		case "birth_date":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.BirthDate).UnmarshalJSON(data))
			}
		case "gender":
			out.Gender = constants.Gender(in.String())
		case "bio":
			if in.IsNull() {
				in.Skip()
				out.Bio = nil
			} else {
				if out.Bio == nil {
					out.Bio = new(string)
				}
				*out.Bio = string(in.String())
			}
		case "city":
			if in.IsNull() {
				in.Skip()
				out.City = nil
			} else {
				if out.City == nil {
					out.City = new(string)
				}
				*out.City = string(in.String())
			}
		case "artist":
			if in.IsNull() {
				in.Skip()
				out.Artist = nil
			} else {
				if out.Artist == nil {
					out.Artist = new(string)
				}
				*out.Artist = string(in.String())
			}
		case "quote":
			if in.IsNull() {
				in.Skip()
				out.Quote = nil
			} else {
				if out.Quote == nil {
					out.Quote = new(string)
				}
				*out.Quote = string(in.String())
			}
		case "is_verified":
			out.IsVerified = bool(in.Bool())
		case "is_premium":
			out.IsPremium = bool(in.Bool())
		case "super_likes_count":
			out.SuperLikesCount = int(in.Int())
		case "last_active":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.LastActive).UnmarshalJSON(data))
			}
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e1087fdEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(out *jwriter.Writer, in User) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	if in.Phone != nil {
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		out.String(string(*in.Phone))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"birth_date\":"
		out.RawString(prefix)
		out.Raw((in.BirthDate).MarshalJSON())
	}
	{
		const prefix string = ",\"gender\":"
		out.RawString(prefix)
		out.String(string(in.Gender))
	}
	if in.Bio != nil {
		const prefix string = ",\"bio\":"
		out.RawString(prefix)
		out.String(string(*in.Bio))
	}
	if in.City != nil {
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(*in.City))
	}
	if in.Artist != nil {
		const prefix string = ",\"artist\":"
		out.RawString(prefix)
		out.String(string(*in.Artist))
	}
	if in.Quote != nil {
		const prefix string = ",\"quote\":"
		out.RawString(prefix)
		out.String(string(*in.Quote))
	}
	{
		const prefix string = ",\"is_verified\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsVerified))
	}
	{
		const prefix string = ",\"is_premium\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsPremium))
	}
	{
		const prefix string = ",\"super_likes_count\":"
		out.RawString(prefix)
		out.Int(int(in.SuperLikesCount))
	}
	{
		const prefix string = ",\"last_active\":"
		out.RawString(prefix)
		out.Raw((in.LastActive).MarshalJSON())
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v User) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e1087fdEncodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *User) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e1087fdDecodeGithubComGoParkMailRu20252RoadTo200BackendInternalDomainEntities(l, v)
}
