// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/core/core.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreService_GetProfile_FullMethodName              = "/core.CoreService/GetProfile"
	CoreService_GetProfileWithRelations_FullMethodName = "/core.CoreService/GetProfileWithRelations"
	CoreService_UpdateProfileInfo_FullMethodName       = "/core.CoreService/UpdateProfileInfo"
	CoreService_UpdatePreferences_FullMethodName       = "/core.CoreService/UpdatePreferences"
	CoreService_UpdateInterests_FullMethodName         = "/core.CoreService/UpdateInterests"
	CoreService_DeletePhoto_FullMethodName             = "/core.CoreService/DeletePhoto"
	CoreService_SetPrimaryPhoto_FullMethodName         = "/core.CoreService/SetPrimaryPhoto"
	CoreService_ReorderPhotos_FullMethodName           = "/core.CoreService/ReorderPhotos"
	CoreService_UploadPhoto_FullMethodName             = "/core.CoreService/UploadPhoto"
	CoreService_ChangePassword_FullMethodName          = "/core.CoreService/ChangePassword"
	CoreService_DeleteAccount_FullMethodName           = "/core.CoreService/DeleteAccount"
	CoreService_GetFeed_FullMethodName                 = "/core.CoreService/GetFeed"
	CoreService_ProcessSwipe_FullMethodName            = "/core.CoreService/ProcessSwipe"
	CoreService_GetUserMatches_FullMethodName          = "/core.CoreService/GetUserMatches"
	CoreService_Unmatch_FullMethodName                 = "/core.CoreService/Unmatch"
	CoreService_CreateStrike_FullMethodName            = "/core.CoreService/CreateStrike"
	CoreService_GetStrike_FullMethodName               = "/core.CoreService/GetStrike"
	CoreService_GetStrikesByUserID_FullMethodName      = "/core.CoreService/GetStrikesByUserID"
	CoreService_GetStrikesByType_FullMethodName        = "/core.CoreService/GetStrikesByType"
	CoreService_GetStrikesByDateRange_FullMethodName   = "/core.CoreService/GetStrikesByDateRange"
	CoreService_UpdateStrikeStatus_FullMethodName      = "/core.CoreService/UpdateStrikeStatus"
	CoreService_DeleteStrike_FullMethodName            = "/core.CoreService/DeleteStrike"
	CoreService_GetUserStrikeStats_FullMethodName      = "/core.CoreService/GetUserStrikeStats"
	CoreService_CreateReport_FullMethodName            = "/core.CoreService/CreateReport"
	CoreService_GetUserReports_FullMethodName          = "/core.CoreService/GetUserReports"
	CoreService_GetUserReport_FullMethodName           = "/core.CoreService/GetUserReport"
	CoreService_GetSupportStats_FullMethodName         = "/core.CoreService/GetSupportStats"
)

// CoreServiceClient is the client API for CoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoreService объединяет Profile, Feed, Swipe и Match функциональность
type CoreServiceClient interface {
	// Profile operations
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	GetProfileWithRelations(ctx context.Context, in *GetProfileWithRelationsRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	UpdateProfileInfo(ctx context.Context, in *UpdateProfileInfoRequest, opts ...grpc.CallOption) (*UpdateProfileInfoResponse, error)
	UpdatePreferences(ctx context.Context, in *UpdatePreferencesRequest, opts ...grpc.CallOption) (*UpdatePreferencesResponse, error)
	UpdateInterests(ctx context.Context, in *UpdateInterestsRequest, opts ...grpc.CallOption) (*UpdateInterestsResponse, error)
	DeletePhoto(ctx context.Context, in *DeletePhotoRequest, opts ...grpc.CallOption) (*DeletePhotoResponse, error)
	SetPrimaryPhoto(ctx context.Context, in *SetPrimaryPhotoRequest, opts ...grpc.CallOption) (*SetPrimaryPhotoResponse, error)
	ReorderPhotos(ctx context.Context, in *ReorderPhotosRequest, opts ...grpc.CallOption) (*ReorderPhotosResponse, error)
	UploadPhoto(ctx context.Context, in *UploadPhotoRequest, opts ...grpc.CallOption) (*UploadPhotoResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error)
	// Feed operations
	GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*GetFeedResponse, error)
	// Swipe operations
	ProcessSwipe(ctx context.Context, in *ProcessSwipeRequest, opts ...grpc.CallOption) (*ProcessSwipeResponse, error)
	// Match operations
	GetUserMatches(ctx context.Context, in *GetUserMatchesRequest, opts ...grpc.CallOption) (*GetUserMatchesResponse, error)
	Unmatch(ctx context.Context, in *UnmatchRequest, opts ...grpc.CallOption) (*UnmatchResponse, error)
	// Strike methods
	CreateStrike(ctx context.Context, in *CreateStrikeRequest, opts ...grpc.CallOption) (*CreateStrikeResponse, error)
	GetStrike(ctx context.Context, in *GetStrikeRequest, opts ...grpc.CallOption) (*GetStrikeResponse, error)
	GetStrikesByUserID(ctx context.Context, in *GetStrikesByUserIDRequest, opts ...grpc.CallOption) (*GetStrikesByUserIDResponse, error)
	GetStrikesByType(ctx context.Context, in *GetStrikesByTypeRequest, opts ...grpc.CallOption) (*GetStrikesByTypeResponse, error)
	GetStrikesByDateRange(ctx context.Context, in *GetStrikesByDateRangeRequest, opts ...grpc.CallOption) (*GetStrikesByDateRangeResponse, error)
	UpdateStrikeStatus(ctx context.Context, in *UpdateStrikeStatusRequest, opts ...grpc.CallOption) (*UpdateStrikeStatusResponse, error)
	DeleteStrike(ctx context.Context, in *DeleteStrikeRequest, opts ...grpc.CallOption) (*DeleteStrikeResponse, error)
	GetUserStrikeStats(ctx context.Context, in *GetUserStrikeStatsRequest, opts ...grpc.CallOption) (*GetUserStrikeStatsResponse, error)
	// Report/Support methods
	CreateReport(ctx context.Context, in *CreateReportRequest, opts ...grpc.CallOption) (*CreateReportResponse, error)
	GetUserReports(ctx context.Context, in *GetUserReportsRequest, opts ...grpc.CallOption) (*GetUserReportsResponse, error)
	GetUserReport(ctx context.Context, in *GetUserReportRequest, opts ...grpc.CallOption) (*GetUserReportResponse, error)
	GetSupportStats(ctx context.Context, in *GetSupportStatsRequest, opts ...grpc.CallOption) (*GetSupportStatsResponse, error)
}

type coreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreServiceClient(cc grpc.ClientConnInterface) CoreServiceClient {
	return &coreServiceClient{cc}
}

func (c *coreServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, CoreService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetProfileWithRelations(ctx context.Context, in *GetProfileWithRelationsRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, CoreService_GetProfileWithRelations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) UpdateProfileInfo(ctx context.Context, in *UpdateProfileInfoRequest, opts ...grpc.CallOption) (*UpdateProfileInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileInfoResponse)
	err := c.cc.Invoke(ctx, CoreService_UpdateProfileInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) UpdatePreferences(ctx context.Context, in *UpdatePreferencesRequest, opts ...grpc.CallOption) (*UpdatePreferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePreferencesResponse)
	err := c.cc.Invoke(ctx, CoreService_UpdatePreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) UpdateInterests(ctx context.Context, in *UpdateInterestsRequest, opts ...grpc.CallOption) (*UpdateInterestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInterestsResponse)
	err := c.cc.Invoke(ctx, CoreService_UpdateInterests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) DeletePhoto(ctx context.Context, in *DeletePhotoRequest, opts ...grpc.CallOption) (*DeletePhotoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePhotoResponse)
	err := c.cc.Invoke(ctx, CoreService_DeletePhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SetPrimaryPhoto(ctx context.Context, in *SetPrimaryPhotoRequest, opts ...grpc.CallOption) (*SetPrimaryPhotoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPrimaryPhotoResponse)
	err := c.cc.Invoke(ctx, CoreService_SetPrimaryPhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ReorderPhotos(ctx context.Context, in *ReorderPhotosRequest, opts ...grpc.CallOption) (*ReorderPhotosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReorderPhotosResponse)
	err := c.cc.Invoke(ctx, CoreService_ReorderPhotos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) UploadPhoto(ctx context.Context, in *UploadPhotoRequest, opts ...grpc.CallOption) (*UploadPhotoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPhotoResponse)
	err := c.cc.Invoke(ctx, CoreService_UploadPhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, CoreService_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAccountResponse)
	err := c.cc.Invoke(ctx, CoreService_DeleteAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*GetFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeedResponse)
	err := c.cc.Invoke(ctx, CoreService_GetFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ProcessSwipe(ctx context.Context, in *ProcessSwipeRequest, opts ...grpc.CallOption) (*ProcessSwipeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessSwipeResponse)
	err := c.cc.Invoke(ctx, CoreService_ProcessSwipe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetUserMatches(ctx context.Context, in *GetUserMatchesRequest, opts ...grpc.CallOption) (*GetUserMatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserMatchesResponse)
	err := c.cc.Invoke(ctx, CoreService_GetUserMatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) Unmatch(ctx context.Context, in *UnmatchRequest, opts ...grpc.CallOption) (*UnmatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnmatchResponse)
	err := c.cc.Invoke(ctx, CoreService_Unmatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) CreateStrike(ctx context.Context, in *CreateStrikeRequest, opts ...grpc.CallOption) (*CreateStrikeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStrikeResponse)
	err := c.cc.Invoke(ctx, CoreService_CreateStrike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetStrike(ctx context.Context, in *GetStrikeRequest, opts ...grpc.CallOption) (*GetStrikeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStrikeResponse)
	err := c.cc.Invoke(ctx, CoreService_GetStrike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetStrikesByUserID(ctx context.Context, in *GetStrikesByUserIDRequest, opts ...grpc.CallOption) (*GetStrikesByUserIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStrikesByUserIDResponse)
	err := c.cc.Invoke(ctx, CoreService_GetStrikesByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetStrikesByType(ctx context.Context, in *GetStrikesByTypeRequest, opts ...grpc.CallOption) (*GetStrikesByTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStrikesByTypeResponse)
	err := c.cc.Invoke(ctx, CoreService_GetStrikesByType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetStrikesByDateRange(ctx context.Context, in *GetStrikesByDateRangeRequest, opts ...grpc.CallOption) (*GetStrikesByDateRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStrikesByDateRangeResponse)
	err := c.cc.Invoke(ctx, CoreService_GetStrikesByDateRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) UpdateStrikeStatus(ctx context.Context, in *UpdateStrikeStatusRequest, opts ...grpc.CallOption) (*UpdateStrikeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStrikeStatusResponse)
	err := c.cc.Invoke(ctx, CoreService_UpdateStrikeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) DeleteStrike(ctx context.Context, in *DeleteStrikeRequest, opts ...grpc.CallOption) (*DeleteStrikeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStrikeResponse)
	err := c.cc.Invoke(ctx, CoreService_DeleteStrike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetUserStrikeStats(ctx context.Context, in *GetUserStrikeStatsRequest, opts ...grpc.CallOption) (*GetUserStrikeStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserStrikeStatsResponse)
	err := c.cc.Invoke(ctx, CoreService_GetUserStrikeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) CreateReport(ctx context.Context, in *CreateReportRequest, opts ...grpc.CallOption) (*CreateReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReportResponse)
	err := c.cc.Invoke(ctx, CoreService_CreateReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetUserReports(ctx context.Context, in *GetUserReportsRequest, opts ...grpc.CallOption) (*GetUserReportsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserReportsResponse)
	err := c.cc.Invoke(ctx, CoreService_GetUserReports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetUserReport(ctx context.Context, in *GetUserReportRequest, opts ...grpc.CallOption) (*GetUserReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserReportResponse)
	err := c.cc.Invoke(ctx, CoreService_GetUserReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetSupportStats(ctx context.Context, in *GetSupportStatsRequest, opts ...grpc.CallOption) (*GetSupportStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSupportStatsResponse)
	err := c.cc.Invoke(ctx, CoreService_GetSupportStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServiceServer is the server API for CoreService service.
// All implementations must embed UnimplementedCoreServiceServer
// for forward compatibility.
//
// CoreService объединяет Profile, Feed, Swipe и Match функциональность
type CoreServiceServer interface {
	// Profile operations
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	GetProfileWithRelations(context.Context, *GetProfileWithRelationsRequest) (*GetProfileResponse, error)
	UpdateProfileInfo(context.Context, *UpdateProfileInfoRequest) (*UpdateProfileInfoResponse, error)
	UpdatePreferences(context.Context, *UpdatePreferencesRequest) (*UpdatePreferencesResponse, error)
	UpdateInterests(context.Context, *UpdateInterestsRequest) (*UpdateInterestsResponse, error)
	DeletePhoto(context.Context, *DeletePhotoRequest) (*DeletePhotoResponse, error)
	SetPrimaryPhoto(context.Context, *SetPrimaryPhotoRequest) (*SetPrimaryPhotoResponse, error)
	ReorderPhotos(context.Context, *ReorderPhotosRequest) (*ReorderPhotosResponse, error)
	UploadPhoto(context.Context, *UploadPhotoRequest) (*UploadPhotoResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	DeleteAccount(context.Context, *DeleteAccountRequest) (*DeleteAccountResponse, error)
	// Feed operations
	GetFeed(context.Context, *GetFeedRequest) (*GetFeedResponse, error)
	// Swipe operations
	ProcessSwipe(context.Context, *ProcessSwipeRequest) (*ProcessSwipeResponse, error)
	// Match operations
	GetUserMatches(context.Context, *GetUserMatchesRequest) (*GetUserMatchesResponse, error)
	Unmatch(context.Context, *UnmatchRequest) (*UnmatchResponse, error)
	// Strike methods
	CreateStrike(context.Context, *CreateStrikeRequest) (*CreateStrikeResponse, error)
	GetStrike(context.Context, *GetStrikeRequest) (*GetStrikeResponse, error)
	GetStrikesByUserID(context.Context, *GetStrikesByUserIDRequest) (*GetStrikesByUserIDResponse, error)
	GetStrikesByType(context.Context, *GetStrikesByTypeRequest) (*GetStrikesByTypeResponse, error)
	GetStrikesByDateRange(context.Context, *GetStrikesByDateRangeRequest) (*GetStrikesByDateRangeResponse, error)
	UpdateStrikeStatus(context.Context, *UpdateStrikeStatusRequest) (*UpdateStrikeStatusResponse, error)
	DeleteStrike(context.Context, *DeleteStrikeRequest) (*DeleteStrikeResponse, error)
	GetUserStrikeStats(context.Context, *GetUserStrikeStatsRequest) (*GetUserStrikeStatsResponse, error)
	// Report/Support methods
	CreateReport(context.Context, *CreateReportRequest) (*CreateReportResponse, error)
	GetUserReports(context.Context, *GetUserReportsRequest) (*GetUserReportsResponse, error)
	GetUserReport(context.Context, *GetUserReportRequest) (*GetUserReportResponse, error)
	GetSupportStats(context.Context, *GetSupportStatsRequest) (*GetSupportStatsResponse, error)
	mustEmbedUnimplementedCoreServiceServer()
}

// UnimplementedCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServiceServer struct{}

func (UnimplementedCoreServiceServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedCoreServiceServer) GetProfileWithRelations(context.Context, *GetProfileWithRelationsRequest) (*GetProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileWithRelations not implemented")
}
func (UnimplementedCoreServiceServer) UpdateProfileInfo(context.Context, *UpdateProfileInfoRequest) (*UpdateProfileInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfileInfo not implemented")
}
func (UnimplementedCoreServiceServer) UpdatePreferences(context.Context, *UpdatePreferencesRequest) (*UpdatePreferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePreferences not implemented")
}
func (UnimplementedCoreServiceServer) UpdateInterests(context.Context, *UpdateInterestsRequest) (*UpdateInterestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInterests not implemented")
}
func (UnimplementedCoreServiceServer) DeletePhoto(context.Context, *DeletePhotoRequest) (*DeletePhotoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePhoto not implemented")
}
func (UnimplementedCoreServiceServer) SetPrimaryPhoto(context.Context, *SetPrimaryPhotoRequest) (*SetPrimaryPhotoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPrimaryPhoto not implemented")
}
func (UnimplementedCoreServiceServer) ReorderPhotos(context.Context, *ReorderPhotosRequest) (*ReorderPhotosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReorderPhotos not implemented")
}
func (UnimplementedCoreServiceServer) UploadPhoto(context.Context, *UploadPhotoRequest) (*UploadPhotoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadPhoto not implemented")
}
func (UnimplementedCoreServiceServer) ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedCoreServiceServer) DeleteAccount(context.Context, *DeleteAccountRequest) (*DeleteAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccount not implemented")
}
func (UnimplementedCoreServiceServer) GetFeed(context.Context, *GetFeedRequest) (*GetFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeed not implemented")
}
func (UnimplementedCoreServiceServer) ProcessSwipe(context.Context, *ProcessSwipeRequest) (*ProcessSwipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessSwipe not implemented")
}
func (UnimplementedCoreServiceServer) GetUserMatches(context.Context, *GetUserMatchesRequest) (*GetUserMatchesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserMatches not implemented")
}
func (UnimplementedCoreServiceServer) Unmatch(context.Context, *UnmatchRequest) (*UnmatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unmatch not implemented")
}
func (UnimplementedCoreServiceServer) CreateStrike(context.Context, *CreateStrikeRequest) (*CreateStrikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStrike not implemented")
}
func (UnimplementedCoreServiceServer) GetStrike(context.Context, *GetStrikeRequest) (*GetStrikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStrike not implemented")
}
func (UnimplementedCoreServiceServer) GetStrikesByUserID(context.Context, *GetStrikesByUserIDRequest) (*GetStrikesByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStrikesByUserID not implemented")
}
func (UnimplementedCoreServiceServer) GetStrikesByType(context.Context, *GetStrikesByTypeRequest) (*GetStrikesByTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStrikesByType not implemented")
}
func (UnimplementedCoreServiceServer) GetStrikesByDateRange(context.Context, *GetStrikesByDateRangeRequest) (*GetStrikesByDateRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStrikesByDateRange not implemented")
}
func (UnimplementedCoreServiceServer) UpdateStrikeStatus(context.Context, *UpdateStrikeStatusRequest) (*UpdateStrikeStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrikeStatus not implemented")
}
func (UnimplementedCoreServiceServer) DeleteStrike(context.Context, *DeleteStrikeRequest) (*DeleteStrikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStrike not implemented")
}
func (UnimplementedCoreServiceServer) GetUserStrikeStats(context.Context, *GetUserStrikeStatsRequest) (*GetUserStrikeStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserStrikeStats not implemented")
}
func (UnimplementedCoreServiceServer) CreateReport(context.Context, *CreateReportRequest) (*CreateReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReport not implemented")
}
func (UnimplementedCoreServiceServer) GetUserReports(context.Context, *GetUserReportsRequest) (*GetUserReportsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserReports not implemented")
}
func (UnimplementedCoreServiceServer) GetUserReport(context.Context, *GetUserReportRequest) (*GetUserReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserReport not implemented")
}
func (UnimplementedCoreServiceServer) GetSupportStats(context.Context, *GetSupportStatsRequest) (*GetSupportStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSupportStats not implemented")
}
func (UnimplementedCoreServiceServer) mustEmbedUnimplementedCoreServiceServer() {}
func (UnimplementedCoreServiceServer) testEmbeddedByValue()                     {}

// UnsafeCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServiceServer will
// result in compilation errors.
type UnsafeCoreServiceServer interface {
	mustEmbedUnimplementedCoreServiceServer()
}

func RegisterCoreServiceServer(s grpc.ServiceRegistrar, srv CoreServiceServer) {
	// If the following call pancis, it indicates UnimplementedCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreService_ServiceDesc, srv)
}

func _CoreService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetProfileWithRelations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileWithRelationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetProfileWithRelations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetProfileWithRelations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetProfileWithRelations(ctx, req.(*GetProfileWithRelationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_UpdateProfileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).UpdateProfileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_UpdateProfileInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).UpdateProfileInfo(ctx, req.(*UpdateProfileInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_UpdatePreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePreferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).UpdatePreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_UpdatePreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).UpdatePreferences(ctx, req.(*UpdatePreferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_UpdateInterests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInterestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).UpdateInterests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_UpdateInterests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).UpdateInterests(ctx, req.(*UpdateInterestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_DeletePhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).DeletePhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_DeletePhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).DeletePhoto(ctx, req.(*DeletePhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SetPrimaryPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPrimaryPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SetPrimaryPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_SetPrimaryPhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SetPrimaryPhoto(ctx, req.(*SetPrimaryPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ReorderPhotos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReorderPhotosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReorderPhotos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReorderPhotos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReorderPhotos(ctx, req.(*ReorderPhotosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_UploadPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).UploadPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_UploadPhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).UploadPhoto(ctx, req.(*UploadPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_DeleteAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).DeleteAccount(ctx, req.(*DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetFeed(ctx, req.(*GetFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ProcessSwipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessSwipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ProcessSwipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ProcessSwipe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ProcessSwipe(ctx, req.(*ProcessSwipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetUserMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetUserMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetUserMatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetUserMatches(ctx, req.(*GetUserMatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_Unmatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).Unmatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_Unmatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).Unmatch(ctx, req.(*UnmatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_CreateStrike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStrikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).CreateStrike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_CreateStrike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).CreateStrike(ctx, req.(*CreateStrikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetStrike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStrikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetStrike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetStrike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetStrike(ctx, req.(*GetStrikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetStrikesByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStrikesByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetStrikesByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetStrikesByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetStrikesByUserID(ctx, req.(*GetStrikesByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetStrikesByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStrikesByTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetStrikesByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetStrikesByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetStrikesByType(ctx, req.(*GetStrikesByTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetStrikesByDateRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStrikesByDateRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetStrikesByDateRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetStrikesByDateRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetStrikesByDateRange(ctx, req.(*GetStrikesByDateRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_UpdateStrikeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStrikeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).UpdateStrikeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_UpdateStrikeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).UpdateStrikeStatus(ctx, req.(*UpdateStrikeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_DeleteStrike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStrikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).DeleteStrike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_DeleteStrike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).DeleteStrike(ctx, req.(*DeleteStrikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetUserStrikeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserStrikeStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetUserStrikeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetUserStrikeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetUserStrikeStats(ctx, req.(*GetUserStrikeStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_CreateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).CreateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_CreateReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).CreateReport(ctx, req.(*CreateReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetUserReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetUserReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetUserReports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetUserReports(ctx, req.(*GetUserReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetUserReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetUserReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetUserReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetUserReport(ctx, req.(*GetUserReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetSupportStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupportStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetSupportStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetSupportStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetSupportStats(ctx, req.(*GetSupportStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreService_ServiceDesc is the grpc.ServiceDesc for CoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.CoreService",
	HandlerType: (*CoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfile",
			Handler:    _CoreService_GetProfile_Handler,
		},
		{
			MethodName: "GetProfileWithRelations",
			Handler:    _CoreService_GetProfileWithRelations_Handler,
		},
		{
			MethodName: "UpdateProfileInfo",
			Handler:    _CoreService_UpdateProfileInfo_Handler,
		},
		{
			MethodName: "UpdatePreferences",
			Handler:    _CoreService_UpdatePreferences_Handler,
		},
		{
			MethodName: "UpdateInterests",
			Handler:    _CoreService_UpdateInterests_Handler,
		},
		{
			MethodName: "DeletePhoto",
			Handler:    _CoreService_DeletePhoto_Handler,
		},
		{
			MethodName: "SetPrimaryPhoto",
			Handler:    _CoreService_SetPrimaryPhoto_Handler,
		},
		{
			MethodName: "ReorderPhotos",
			Handler:    _CoreService_ReorderPhotos_Handler,
		},
		{
			MethodName: "UploadPhoto",
			Handler:    _CoreService_UploadPhoto_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _CoreService_ChangePassword_Handler,
		},
		{
			MethodName: "DeleteAccount",
			Handler:    _CoreService_DeleteAccount_Handler,
		},
		{
			MethodName: "GetFeed",
			Handler:    _CoreService_GetFeed_Handler,
		},
		{
			MethodName: "ProcessSwipe",
			Handler:    _CoreService_ProcessSwipe_Handler,
		},
		{
			MethodName: "GetUserMatches",
			Handler:    _CoreService_GetUserMatches_Handler,
		},
		{
			MethodName: "Unmatch",
			Handler:    _CoreService_Unmatch_Handler,
		},
		{
			MethodName: "CreateStrike",
			Handler:    _CoreService_CreateStrike_Handler,
		},
		{
			MethodName: "GetStrike",
			Handler:    _CoreService_GetStrike_Handler,
		},
		{
			MethodName: "GetStrikesByUserID",
			Handler:    _CoreService_GetStrikesByUserID_Handler,
		},
		{
			MethodName: "GetStrikesByType",
			Handler:    _CoreService_GetStrikesByType_Handler,
		},
		{
			MethodName: "GetStrikesByDateRange",
			Handler:    _CoreService_GetStrikesByDateRange_Handler,
		},
		{
			MethodName: "UpdateStrikeStatus",
			Handler:    _CoreService_UpdateStrikeStatus_Handler,
		},
		{
			MethodName: "DeleteStrike",
			Handler:    _CoreService_DeleteStrike_Handler,
		},
		{
			MethodName: "GetUserStrikeStats",
			Handler:    _CoreService_GetUserStrikeStats_Handler,
		},
		{
			MethodName: "CreateReport",
			Handler:    _CoreService_CreateReport_Handler,
		},
		{
			MethodName: "GetUserReports",
			Handler:    _CoreService_GetUserReports_Handler,
		},
		{
			MethodName: "GetUserReport",
			Handler:    _CoreService_GetUserReport_Handler,
		},
		{
			MethodName: "GetSupportStats",
			Handler:    _CoreService_GetSupportStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/core/core.proto",
}
