// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/core/core.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreService_GetProfile_FullMethodName        = "/core.CoreService/GetProfile"
	CoreService_UpdateProfileInfo_FullMethodName = "/core.CoreService/UpdateProfileInfo"
	CoreService_UpdatePreferences_FullMethodName = "/core.CoreService/UpdatePreferences"
	CoreService_UpdateInterests_FullMethodName   = "/core.CoreService/UpdateInterests"
	CoreService_DeletePhoto_FullMethodName       = "/core.CoreService/DeletePhoto"
	CoreService_SetPrimaryPhoto_FullMethodName   = "/core.CoreService/SetPrimaryPhoto"
	CoreService_ReorderPhotos_FullMethodName     = "/core.CoreService/ReorderPhotos"
	CoreService_GetFeed_FullMethodName           = "/core.CoreService/GetFeed"
	CoreService_ProcessSwipe_FullMethodName      = "/core.CoreService/ProcessSwipe"
	CoreService_GetUserMatches_FullMethodName    = "/core.CoreService/GetUserMatches"
	CoreService_Unmatch_FullMethodName           = "/core.CoreService/Unmatch"
)

// CoreServiceClient is the client API for CoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CoreService объединяет Profile, Feed, Swipe и Match функциональность
type CoreServiceClient interface {
	// Profile operations
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	UpdateProfileInfo(ctx context.Context, in *UpdateProfileInfoRequest, opts ...grpc.CallOption) (*UpdateProfileInfoResponse, error)
	UpdatePreferences(ctx context.Context, in *UpdatePreferencesRequest, opts ...grpc.CallOption) (*UpdatePreferencesResponse, error)
	UpdateInterests(ctx context.Context, in *UpdateInterestsRequest, opts ...grpc.CallOption) (*UpdateInterestsResponse, error)
	DeletePhoto(ctx context.Context, in *DeletePhotoRequest, opts ...grpc.CallOption) (*DeletePhotoResponse, error)
	SetPrimaryPhoto(ctx context.Context, in *SetPrimaryPhotoRequest, opts ...grpc.CallOption) (*SetPrimaryPhotoResponse, error)
	ReorderPhotos(ctx context.Context, in *ReorderPhotosRequest, opts ...grpc.CallOption) (*ReorderPhotosResponse, error)
	// Feed operations
	GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*GetFeedResponse, error)
	// Swipe operations
	ProcessSwipe(ctx context.Context, in *ProcessSwipeRequest, opts ...grpc.CallOption) (*ProcessSwipeResponse, error)
	// Match operations
	GetUserMatches(ctx context.Context, in *GetUserMatchesRequest, opts ...grpc.CallOption) (*GetUserMatchesResponse, error)
	Unmatch(ctx context.Context, in *UnmatchRequest, opts ...grpc.CallOption) (*UnmatchResponse, error)
}

type coreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreServiceClient(cc grpc.ClientConnInterface) CoreServiceClient {
	return &coreServiceClient{cc}
}

func (c *coreServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, CoreService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) UpdateProfileInfo(ctx context.Context, in *UpdateProfileInfoRequest, opts ...grpc.CallOption) (*UpdateProfileInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileInfoResponse)
	err := c.cc.Invoke(ctx, CoreService_UpdateProfileInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) UpdatePreferences(ctx context.Context, in *UpdatePreferencesRequest, opts ...grpc.CallOption) (*UpdatePreferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePreferencesResponse)
	err := c.cc.Invoke(ctx, CoreService_UpdatePreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) UpdateInterests(ctx context.Context, in *UpdateInterestsRequest, opts ...grpc.CallOption) (*UpdateInterestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInterestsResponse)
	err := c.cc.Invoke(ctx, CoreService_UpdateInterests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) DeletePhoto(ctx context.Context, in *DeletePhotoRequest, opts ...grpc.CallOption) (*DeletePhotoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePhotoResponse)
	err := c.cc.Invoke(ctx, CoreService_DeletePhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) SetPrimaryPhoto(ctx context.Context, in *SetPrimaryPhotoRequest, opts ...grpc.CallOption) (*SetPrimaryPhotoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPrimaryPhotoResponse)
	err := c.cc.Invoke(ctx, CoreService_SetPrimaryPhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ReorderPhotos(ctx context.Context, in *ReorderPhotosRequest, opts ...grpc.CallOption) (*ReorderPhotosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReorderPhotosResponse)
	err := c.cc.Invoke(ctx, CoreService_ReorderPhotos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetFeed(ctx context.Context, in *GetFeedRequest, opts ...grpc.CallOption) (*GetFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeedResponse)
	err := c.cc.Invoke(ctx, CoreService_GetFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) ProcessSwipe(ctx context.Context, in *ProcessSwipeRequest, opts ...grpc.CallOption) (*ProcessSwipeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessSwipeResponse)
	err := c.cc.Invoke(ctx, CoreService_ProcessSwipe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) GetUserMatches(ctx context.Context, in *GetUserMatchesRequest, opts ...grpc.CallOption) (*GetUserMatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserMatchesResponse)
	err := c.cc.Invoke(ctx, CoreService_GetUserMatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreServiceClient) Unmatch(ctx context.Context, in *UnmatchRequest, opts ...grpc.CallOption) (*UnmatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnmatchResponse)
	err := c.cc.Invoke(ctx, CoreService_Unmatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServiceServer is the server API for CoreService service.
// All implementations must embed UnimplementedCoreServiceServer
// for forward compatibility.
//
// CoreService объединяет Profile, Feed, Swipe и Match функциональность
type CoreServiceServer interface {
	// Profile operations
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	UpdateProfileInfo(context.Context, *UpdateProfileInfoRequest) (*UpdateProfileInfoResponse, error)
	UpdatePreferences(context.Context, *UpdatePreferencesRequest) (*UpdatePreferencesResponse, error)
	UpdateInterests(context.Context, *UpdateInterestsRequest) (*UpdateInterestsResponse, error)
	DeletePhoto(context.Context, *DeletePhotoRequest) (*DeletePhotoResponse, error)
	SetPrimaryPhoto(context.Context, *SetPrimaryPhotoRequest) (*SetPrimaryPhotoResponse, error)
	ReorderPhotos(context.Context, *ReorderPhotosRequest) (*ReorderPhotosResponse, error)
	// Feed operations
	GetFeed(context.Context, *GetFeedRequest) (*GetFeedResponse, error)
	// Swipe operations
	ProcessSwipe(context.Context, *ProcessSwipeRequest) (*ProcessSwipeResponse, error)
	// Match operations
	GetUserMatches(context.Context, *GetUserMatchesRequest) (*GetUserMatchesResponse, error)
	Unmatch(context.Context, *UnmatchRequest) (*UnmatchResponse, error)
	mustEmbedUnimplementedCoreServiceServer()
}

// UnimplementedCoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServiceServer struct{}

func (UnimplementedCoreServiceServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedCoreServiceServer) UpdateProfileInfo(context.Context, *UpdateProfileInfoRequest) (*UpdateProfileInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfileInfo not implemented")
}
func (UnimplementedCoreServiceServer) UpdatePreferences(context.Context, *UpdatePreferencesRequest) (*UpdatePreferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePreferences not implemented")
}
func (UnimplementedCoreServiceServer) UpdateInterests(context.Context, *UpdateInterestsRequest) (*UpdateInterestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInterests not implemented")
}
func (UnimplementedCoreServiceServer) DeletePhoto(context.Context, *DeletePhotoRequest) (*DeletePhotoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePhoto not implemented")
}
func (UnimplementedCoreServiceServer) SetPrimaryPhoto(context.Context, *SetPrimaryPhotoRequest) (*SetPrimaryPhotoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPrimaryPhoto not implemented")
}
func (UnimplementedCoreServiceServer) ReorderPhotos(context.Context, *ReorderPhotosRequest) (*ReorderPhotosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReorderPhotos not implemented")
}
func (UnimplementedCoreServiceServer) GetFeed(context.Context, *GetFeedRequest) (*GetFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeed not implemented")
}
func (UnimplementedCoreServiceServer) ProcessSwipe(context.Context, *ProcessSwipeRequest) (*ProcessSwipeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessSwipe not implemented")
}
func (UnimplementedCoreServiceServer) GetUserMatches(context.Context, *GetUserMatchesRequest) (*GetUserMatchesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserMatches not implemented")
}
func (UnimplementedCoreServiceServer) Unmatch(context.Context, *UnmatchRequest) (*UnmatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unmatch not implemented")
}
func (UnimplementedCoreServiceServer) mustEmbedUnimplementedCoreServiceServer() {}
func (UnimplementedCoreServiceServer) testEmbeddedByValue()                     {}

// UnsafeCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServiceServer will
// result in compilation errors.
type UnsafeCoreServiceServer interface {
	mustEmbedUnimplementedCoreServiceServer()
}

func RegisterCoreServiceServer(s grpc.ServiceRegistrar, srv CoreServiceServer) {
	// If the following call pancis, it indicates UnimplementedCoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreService_ServiceDesc, srv)
}

func _CoreService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_UpdateProfileInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).UpdateProfileInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_UpdateProfileInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).UpdateProfileInfo(ctx, req.(*UpdateProfileInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_UpdatePreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePreferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).UpdatePreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_UpdatePreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).UpdatePreferences(ctx, req.(*UpdatePreferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_UpdateInterests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInterestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).UpdateInterests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_UpdateInterests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).UpdateInterests(ctx, req.(*UpdateInterestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_DeletePhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).DeletePhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_DeletePhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).DeletePhoto(ctx, req.(*DeletePhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_SetPrimaryPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPrimaryPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).SetPrimaryPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_SetPrimaryPhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).SetPrimaryPhoto(ctx, req.(*SetPrimaryPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ReorderPhotos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReorderPhotosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ReorderPhotos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ReorderPhotos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ReorderPhotos(ctx, req.(*ReorderPhotosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetFeed(ctx, req.(*GetFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_ProcessSwipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessSwipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).ProcessSwipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_ProcessSwipe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).ProcessSwipe(ctx, req.(*ProcessSwipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_GetUserMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).GetUserMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_GetUserMatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).GetUserMatches(ctx, req.(*GetUserMatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreService_Unmatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServiceServer).Unmatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreService_Unmatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServiceServer).Unmatch(ctx, req.(*UnmatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreService_ServiceDesc is the grpc.ServiceDesc for CoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.CoreService",
	HandlerType: (*CoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfile",
			Handler:    _CoreService_GetProfile_Handler,
		},
		{
			MethodName: "UpdateProfileInfo",
			Handler:    _CoreService_UpdateProfileInfo_Handler,
		},
		{
			MethodName: "UpdatePreferences",
			Handler:    _CoreService_UpdatePreferences_Handler,
		},
		{
			MethodName: "UpdateInterests",
			Handler:    _CoreService_UpdateInterests_Handler,
		},
		{
			MethodName: "DeletePhoto",
			Handler:    _CoreService_DeletePhoto_Handler,
		},
		{
			MethodName: "SetPrimaryPhoto",
			Handler:    _CoreService_SetPrimaryPhoto_Handler,
		},
		{
			MethodName: "ReorderPhotos",
			Handler:    _CoreService_ReorderPhotos_Handler,
		},
		{
			MethodName: "GetFeed",
			Handler:    _CoreService_GetFeed_Handler,
		},
		{
			MethodName: "ProcessSwipe",
			Handler:    _CoreService_ProcessSwipe_Handler,
		},
		{
			MethodName: "GetUserMatches",
			Handler:    _CoreService_GetUserMatches_Handler,
		},
		{
			MethodName: "Unmatch",
			Handler:    _CoreService_Unmatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/core/core.proto",
}
