app:
  host: 0.0.0.0
  port: 8084
  prefix: /api/v1
  SwaggerPath: ./data/docs/chat.json

  cors:
    allowed_origins:
      - http://127.0.0.1:8001
      - http://localhost:8001
      - http://217.16.17.116:8001

  logger:
    level: DEBUG

  postgres:
    host: PG_HOST
    port: PG_PORT
    base: PG_BASE
    user: PG_USER
    password: PG_PSWD

  redis:
    host: RD_HOST
    port: RD_PORT
    base: RD_BASE
    password: RD_PSWD

  chat_service:
    port: "50053"
